# Book N-Gram Feature Extractor
Extracts the top 100 unigrams, bigrams, and trigrams from each book `.txt` file.
Used for genre classification feature engineering.

In [73]:
import re
import os
import pandas as pd
from collections import Counter
from nltk.util import ngrams
from nltk.corpus import stopwords
import nltk

nltk.download('stopwords', quiet=True)
nltk.download('punkt', quiet=True)

True

## Configuration
Edit the `BOOKS` dictionary to match your `.txt` filenames and genres.
Place all `.txt` files in the same folder as this notebook (or update `BOOKS_DIR`).

In [ ]:
# --- Configuration ---
BOOKS_DIR = "KnownBooks"   # Folder containing the .txt files
EXTRACT_N = 500            # Top n-grams to extract per book (candidates for genre aggregation)
TOP_N     = 100            # Top n-grams to keep per genre (final vocabulary)

BOOKS = {
    # biography (5 books)
    "AutobiographyOfBenjaminFranklin":  "biography",
    "LifeOfKingEdwardVII":              "biography",
    "NarrativeOfFrederickDouglass":     "biography",
    "StoryOfMyLife":                    "biography",
    "AutobiographyOfCharlesDarwin":     "biography",
    # fantasy (5 books)
    "TheWonderfulWizardOfOz":           "fantasy",
    "AliceInWonderland":                "fantasy",
    "ThroughTheLookingGlass":           "fantasy",
    "GrimmsFairyTales":                 "fantasy",
    "GulliversTravels":                 "fantasy",
    # horror (5 books)
    "Frankenstein":                     "horror",
    "CallOfCthulu":                     "horror",
    "Dracula":                          "horror",
    "TalesOfPoe":                       "horror",
    "DrJekyllAndMrHyde":                "horror",
    # romance (5 books)
    "PrideAndPrejudice":                "romance",
    "RomeoAndJuliet":                   "romance",
    "JaneEyre":                         "romance",
    "WutheringHeights":                 "romance",
    "SenseAndSensibility":              "romance",
    # sci-fi (5 books)
    "OnTheTrailOfTheSpacePirates":      "sci-fi",
    "PlagueShip":                       "sci-fi",
    "TheWarOfTheWorlds":                "sci-fi",
    "TheTimeMachine":                   "sci-fi",
    "TwentyThousandLeagues":            "sci-fi",
}

## Clean Raw Text Files (Project Gutenberg)
Strips the standard Project Gutenberg header and footer boilerplate from each `.txt` file
and saves cleaned versions as `<BookName>_clean.txt` in the same directory.
Run this once before extracting n-grams.

In [75]:
import re
import os

# Project Gutenberg delimiter patterns
START_PATTERN = re.compile(r'\*{3}\s*START OF THE PROJECT GUTENBERG EBOOK[^\n]*\*{3}', re.IGNORECASE)
END_PATTERN   = re.compile(r'\*{3}\s*END OF THE PROJECT GUTENBERG EBOOK[^\n]*\*{3}',   re.IGNORECASE)

def clean_gutenberg(filename):
    """
    Strip Project Gutenberg header and footer from a .txt file.
    Saves the cleaned text as <filename>_clean.txt.
    Returns the cleaned text as a string.
    """
    path = os.path.join(BOOKS_DIR, filename + '.txt')
    with open(path, 'r', encoding='utf-8', errors='ignore') as f:
        raw = f.read()

    # Find the start marker
    start_match = START_PATTERN.search(raw)
    if start_match:
        text = raw[start_match.end():]
    else:
        print(f'  [WARNING] No START marker found in {filename} — using full text')
        text = raw

    # Find the end marker
    end_match = END_PATTERN.search(text)
    if end_match:
        text = text[:end_match.start()]
    else:
        print(f'  [WARNING] No END marker found in {filename} — keeping text until EOF')

    text = text.strip()

    # Save cleaned version
    out_path = os.path.join(BOOKS_DIR, filename + '_clean.txt')
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(text)

    original_words = len(raw.split())
    cleaned_words  = len(text.split())
    removed_words  = original_words - cleaned_words
    print(f'  {filename}: {original_words:,} → {cleaned_words:,} words  (removed {removed_words:,} boilerplate words)')
    return text

print('Cleaning Project Gutenberg boilerplate...\n')
for book in BOOKS:
    clean_gutenberg(book)

print('\nCleaned files saved as <BookName>_clean.txt')

Cleaning Project Gutenberg boilerplate...

  AutobiographyOfBenjaminFranklin: 79,264 → 76,203 words  (removed 3,061 boilerplate words)
  LifeOfKingEdwardVII: 150,777 → 147,715 words  (removed 3,062 boilerplate words)
  NarrativeOfFrederickDouglass: 43,819 → 40,750 words  (removed 3,069 boilerplate words)
  StoryOfMyLife: 137,927 → 134,873 words  (removed 3,054 boilerplate words)
  AutobiographyOfCharlesDarwin: 25,733 → 22,684 words  (removed 3,049 boilerplate words)
  TheWonderfulWizardOfOz: 42,692 → 39,649 words  (removed 3,043 boilerplate words)
  AliceInWonderland: 29,569 → 26,525 words  (removed 3,044 boilerplate words)
  ThroughTheLookingGlass: 32,789 → 29,752 words  (removed 3,037 boilerplate words)
  GrimmsFairyTales: 104,156 → 101,111 words  (removed 3,045 boilerplate words)
  GulliversTravels: 108,140 → 105,079 words  (removed 3,061 boilerplate words)
  Frankenstein: 78,106 → 75,042 words  (removed 3,064 boilerplate words)
  CallOfCthulu: 15,029 → 11,968 words  (removed 3,061 boilerplate words)
  Dracula: 164,356 → 161,321 words  (removed 3,035 boilerplate words)
  TalesOfPoe: 98,105 → 95,043 words  (removed 3,062 boilerplate words)
  DrJekyllAndMrHyde: 28,693 → 25,631 words  (removed 3,062 boilerplate words)
  PrideAndPrejudice: 130,415 → 127,359 words  (removed 3,056 boilerplate words)
  RomeoAndJuliet: 29,005 → 25,958 words  (removed 3,047 boilerplate words)
  JaneEyre: 188,435 → 185,390 words  (removed 3,045 boilerplate words)
  WutheringHeights: 118,978 → 115,945 words  (removed 3,033 boilerplate words)
  SenseAndSensibility: 121,894 → 118,860 words  (removed 3,034 boilerplate words)
  OnTheTrailOfTheSpacePirates: 55,595 → 52,524 words  (removed 3,071 boilerplate words)
  PlagueShip: 63,083 → 60,036 words  (removed 3,047 boilerplate words)
  TheWarOfTheWorlds: 63,118 → 60,075 words  (removed 3,043 boilerplate words)
  TheTimeMachine: 35,488 → 32,453 words  (removed 3,035 boilerplate words)
  TwentyThousandLeagues: 107,726 → 104,672 words  (removed 3,054 boilerplate words)

Cleaned files saved as <BookName>_clean.txt

## Helper Functions

In [76]:
STOP_WORDS = set(stopwords.words('english'))

def load_text(filename):
    """Read a .txt file and return its contents as a string."""
    path = os.path.join(BOOKS_DIR, filename + "_clean.txt")
    with open(path, 'r', encoding='utf-8', errors='ignore') as f:
        return f.read()

def tokenize(text):
    """Lowercase, strip punctuation, remove stop words."""
    words = re.findall(r'[a-z]+', text.lower())
    return [w for w in words if w not in STOP_WORDS and len(w) > 1]

def top_ngrams(tokens, n, top_n=TOP_N):
    """Return the top_n most common n-grams as a list of (ngram_string, count) tuples."""
    counts = Counter(ngrams(tokens, n))
    return [(' '.join(gram), count) for gram, count in counts.most_common(top_n)]

## Extract N-Grams for All Books

In [77]:
results = {}  # { book_name: { 'genre': ..., 'unigrams': [...], 'bigrams': [...], 'trigrams': [...] } }

for book, genre in BOOKS.items():
    print(f"Processing: {book} ({genre})...")
    text   = load_text(book)
    tokens = tokenize(text)

    results[book] = {
        'genre':    genre,
        'unigrams': top_ngrams(tokens, 1, top_n=EXTRACT_N),
        'bigrams':  top_ngrams(tokens, 2, top_n=EXTRACT_N),
        'trigrams': top_ngrams(tokens, 3, top_n=EXTRACT_N),
    }

print("\nDone!")

Processing: AutobiographyOfBenjaminFranklin (biography)...
Processing: LifeOfKingEdwardVII (biography)...
Processing: NarrativeOfFrederickDouglass (biography)...
Processing: StoryOfMyLife (biography)...
Processing: AutobiographyOfCharlesDarwin (biography)...
Processing: TheWonderfulWizardOfOz (fantasy)...
Processing: AliceInWonderland (fantasy)...
Processing: ThroughTheLookingGlass (fantasy)...
Processing: GrimmsFairyTales (fantasy)...
Processing: GulliversTravels (fantasy)...
Processing: Frankenstein (horror)...
Processing: CallOfCthulu (horror)...
Processing: Dracula (horror)...
Processing: TalesOfPoe (horror)...
Processing: DrJekyllAndMrHyde (horror)...
Processing: PrideAndPrejudice (romance)...
Processing: RomeoAndJuliet (romance)...
Processing: JaneEyre (romance)...
Processing: WutheringHeights (romance)...
Processing: SenseAndSensibility (romance)...
Processing: OnTheTrailOfTheSpacePirates (sci-fi)...
Processing: PlagueShip (sci-fi)...
Processing: TheWarOfTheWorlds (sci-fi)...
Processing: TheTimeMachine (sci-fi)...
Processing: TwentyThousandLeagues (sci-fi)...

Done!

## Character Name Filtering
Uses NLTK's curated first-name corpus (~7,900 names) to remove any n-gram
whose tokens match a common English given name. This prevents the model from
memorising character names (e.g. *dorothy*, *darcy*, *victor*) instead of
learning genre signals.

In [78]:
nltk.download('names', quiet=True)
from nltk.corpus import names as nltk_names

# Curated list of ~7,900 common English given names (male + female)
PERSON_NAMES = set(n.lower() for n in nltk_names.words())
print(f"Loaded {len(PERSON_NAMES):,} common first names for filtering.")

removal_log = {}

print("\nFiltering n-grams that contain character first names...\n")
for book in BOOKS:
    removed = {'unigrams': [], 'bigrams': [], 'trigrams': []}

    for ngram_type in ['unigrams', 'bigrams', 'trigrams']:
        kept = []
        for ngram, count in results[book][ngram_type]:
            if any(t in PERSON_NAMES for t in ngram.split()):
                removed[ngram_type].append((ngram, count))
            else:
                kept.append((ngram, count))
        results[book][ngram_type] = kept

    removal_log[book] = removed
    n_removed  = sum(len(removed[k]) for k in removed)
    names_hit  = sorted({t for k in removed
                           for ngram, _ in removed[k]
                           for t in ngram.split() if t in PERSON_NAMES})
    print(f"  {book}")
    print(f"    Names matched : {names_hit}")
    print(f"    N-grams removed: {n_removed}  "
          f"({len(removed['unigrams'])} uni / {len(removed['bigrams'])} bi / {len(removed['trigrams'])} tri)\n")

print("Filtering complete — results dict updated.")

Loaded 7,576 common first names for filtering.

Filtering n-grams that contain character first names...

  AutobiographyOfBenjaminFranklin
    Names matched : ['abraham', 'benjamin', 'bishop', 'boyd', 'bradford', 'brian', 'carry', 'case', 'chandler', 'charles', 'christ', 'coleman', 'collins', 'david', 'denny', 'drew', 'ford', 'fortune', 'france', 'frank', 'franklin', 'french', 'george', 'gilbert', 'godfrey', 'grace', 'grant', 'hamilton', 'harry', 'henry', 'hope', 'james', 'jefferson', 'john', 'june', 'king', 'louis', 'mark', 'may', 'miles', 'modesty', 'morris', 'norris', 'page', 'paul', 'penn', 'peter', 'quincy', 'quinn', 'ralph', 'richard', 'robert', 'rose', 'royal', 'samuel', 'saw', 'say', 'see', 'shirley', 'smith', 'son', 'sterling', 'temple', 'thomas', 'town', 'vi', 'way', 'webb', 'west', 'william', 'wilson', 'woodrow', 'wyndham']
    N-grams removed: 247  (27 uni / 77 bi / 143 tri)

  LifeOfKingEdwardVII
    Names matched : ['abbey', 'albert', 'alexandra', 'alfred', 'alice', 'april', 'arthur', 'august', 'barton', 'bishop', 'canada', 'case', 'cecil', 'charles', 'christ', 'christian', 'churchill', 'clarence', 'dean', 'del', 'derby', 'diamond', 'duke', 'earl', 'edmund', 'edward', 'ellis', 'ernest', 'france', 'francis', 'frederick', 'french', 'george', 'gordon', 'hall', 'harcourt', 'helena', 'henry', 'hope', 'james', 'john', 'june', 'king', 'lawrence', 'leighton', 'lev', 'lion', 'lorne', 'louis', 'louise', 'love', 'major', 'marcus', 'marshal', 'mary', 'may', 'mayor', 'merry', 'morley', 'nova', 'paul', 'philippe', 'prince', 'randolph', 'richard', 'robert', 'roman', 'rose', 'royal', 'samuel', 'saw', 'saxe', 'say', 'see', 'si', 'son', 'spencer', 'stafford', 'stanley', 'star', 'steward', 'sutherland', 'thomas', 'town', 'val', 'vi', 'victor', 'victoria', 'way', 'west', 'wilfrid', 'william']
    N-grams removed: 509  (39 uni / 188 bi / 282 tri)

  NarrativeOfFrederickDouglass
    Names matched : ['andrew', 'anna', 'anthony', 'august', 'augustus', 'bailey', 'barney', 'bay', 'bear', 'camel', 'case', 'david', 'douglass', 'drew', 'easton', 'edward', 'else', 'faith', 'fan', 'fred', 'frederick', 'gardner', 'glad', 'hamilton', 'harris', 'harrison', 'henry', 'hester', 'honor', 'hope', 'hugh', 'john', 'joy', 'king', 'lay', 'lloyd', 'love', 'lucretia', 'luther', 'martin', 'mason', 'may', 'mercy', 'michael', 'miles', 'murray', 'nathan', 'ned', 'noble', 'patrick', 'red', 'rice', 'rich', 'rod', 'samuel', 'sandy', 'saw', 'say', 'see', 'son', 'talbot', 'thomas', 'town', 'vi', 'washington', 'way', 'wendell', 'william', 'wood', 'wye', 'yard']
    N-grams removed: 192  (36 uni / 65 bi / 91 tri)

  StoryOfMyLife
    Names matched : ['adams', 'albert', 'alexander', 'anne', 'april', 'arthur', 'bell', 'bird', 'birdie', 'bishop', 'brooks', 'caesar', 'caroline', 'carrie', 'cat', 'charles', 'cherry', 'claus', 'derby', 'doll', 'dudley', 'edward', 'else', 'ethel', 'eugene', 'everett', 'fern', 'florence', 'frank', 'french', 'glad', 'graham', 'hale', 'happy', 'helen', 'hope', 'horace', 'ivy', 'jack', 'john', 'joy', 'june', 'kate', 'keith', 'king', 'la', 'lamb', 'laura', 'laurence', 'lay', 'love', 'margaret', 'mark', 'martha', 'may', 'michael', 'mildred', 'nancy', 'nicholas', 'oliver', 'radcliffe', 'ragnhild', 'robin', 'roman', 'rose', 'samuel', 'sarah', 'saw', 'say', 'see', 'sophia', 'sullivan', 'sunshine', 'wade', 'warner', 'washington', 'way', 'wendell', 'wilhelm', 'william', 'wright']
    N-grams removed: 333  (26 uni / 122 bi / 185 tri)

  AutobiographyOfCharlesDarwin
    Names matched : ['bird', 'butler', 'case', 'catherine', 'charles', 'christian', 'coral', 'darwin', 'del', 'else', 'fitz', 'flower', 'francis', 'grant', 'gray', 'herschel', 'hope', 'james', 'josiah', 'king', 'leighton', 'love', 'major', 'may', 'miles', 'robert', 'rock', 'roy', 'royal', 'saw', 'say', 'see', 'son', 'velvet', 'wallace', 'way', 'worth']
    N-grams removed: 140  (16 uni / 44 bi / 80 tri)

  TheWonderfulWizardOfOz
    Names matched : ['art', 'carry', 'dorothy', 'em', 'forest', 'fortune', 'frank', 'gates', 'glad', 'grant', 'gray', 'happy', 'henry', 'hill', 'hope', 'joy', 'king', 'lay', 'lion', 'love', 'mark', 'may', 'miles', 'poppy', 'red', 'rich', 'saw', 'say', 'see', 'sky', 'vi', 'wait', 'way', 'west', 'wood', 'woodman']
    N-grams removed: 285  (28 uni / 114 bi / 143 tri)

  AliceInWonderland
    Names matched : ['alice', 'ann', 'beau', 'bill', 'carroll', 'cat', 'daisy', 'dinah', 'edwin', 'else', 'fan', 'fancy', 'french', 'glad', 'hall', 'king', 'lewis', 'lory', 'mary', 'may', 'rose', 'saw', 'say', 'see', 'vi', 'way', 'william', 'wood', 'worth']
    N-grams removed: 275  (18 uni / 109 bi / 148 tri)

  ThroughTheLookingGlass
    Names matched : ['alice', 'art', 'brook', 'carroll', 'cat', 'daisy', 'dee', 'deny', 'dinah', 'else', 'fawn', 'forest', 'glad', 'glory', 'happy', 'hill', 'hope', 'king', 'kitty', 'lewis', 'lily', 'lion', 'love', 'may', 'red', 'rose', 'ruddy', 'saw', 'saxon', 'say', 'see', 'shadow', 'storm', 'sunny', 'town', 'vi', 'wait', 'wake', 'way', 'wilt', 'win', 'wood', 'worth']
    N-grams removed: 351  (26 uni / 137 bi / 188 tri)

  GrimmsFairyTales
    Names matched : ['art', 'bear', 'bird', 'bride', 'carry', 'carter', 'cat', 'dove', 'drew', 'else', 'elsie', 'er', 'flower', 'forest', 'fox', 'frederick', 'gardener', 'glad', 'goose', 'gretel', 'grove', 'hans', 'hansel', 'happy', 'hazel', 'joy', 'king', 'lay', 'lina', 'lion', 'love', 'marleen', 'may', 'merry', 'penny', 'prince', 'raven', 'red', 'rich', 'roland', 'rose', 'royal', 'saw', 'say', 'see', 'shepherd', 'son', 'star', 'tailor', 'tom', 'town', 'wait', 'way', 'willow', 'wolf', 'wood', 'wren']
    N-grams removed: 276  (43 uni / 95 bi / 138 tri)

  GulliversTravels
    Names matched : ['april', 'august', 'carry', 'chance', 'dean', 'drew', 'fortune', 'hope', 'john', 'jonathan', 'june', 'king', 'lay', 'lemuel', 'love', 'may', 'miles', 'nicholas', 'noble', 'park', 'patrick', 'pedro', 'pen', 'prince', 'royal', 'saw', 'say', 'see', 'storm', 'sue', 'town', 'van', 'vi', 'way', 'west', 'worthy']
    N-grams removed: 94  (17 uni / 27 bi / 50 tri)

  Frankenstein
    Names matched : ['agatha', 'angel', 'august', 'beaufort', 'caroline', 'cornelius', 'drew', 'elizabeth', 'else', 'felix', 'fortune', 'geneva', 'godwin', 'happy', 'henry', 'homer', 'hope', 'joy', 'justine', 'lacey', 'lay', 'love', 'magnus', 'margaret', 'mary', 'may', 'miles', 'noble', 'rose', 'sal', 'saw', 'say', 'see', 'shelley', 'son', 'temple', 'thomas', 'town', 'victor', 'walton', 'way', 'william', 'wood']
    N-grams removed: 133  (23 uni / 50 bi / 60 tri)

  CallOfCthulu
    Names matched : ['algernon', 'april', 'art', 'case', 'clay', 'collins', 'else', 'emma', 'fancy', 'fleur', 'francis', 'george', 'gustaf', 'hill', 'hope', 'lay', 'may', 'rock', 'saw', 'say', 'see', 'sky', 'storm', 'sydney', 'thurston', 'tobey', 'tom', 'trip', 'way', 'wayland', 'webb', 'west']
    N-grams removed: 113  (21 uni / 43 bi / 49 tri)

  Dracula
    Names matched : ['abraham', 'agatha', 'art', 'arthur', 'august', 'bay', 'brandy', 'cal', 'candy', 'carter', 'case', 'catherine', 'chance', 'che', 'cliff', 'dawn', 'drew', 'else', 'glad', 'hall', 'happy', 'hill', 'hope', 'john', 'jonathan', 'joseph', 'king', 'lay', 'love', 'lucy', 'mary', 'may', 'mina', 'mitchell', 'morris', 'murray', 'peter', 'pier', 'quincey', 'red', 'robin', 'rose', 'samuel', 'saw', 'say', 'see', 'son', 'tate', 'van', 'vi', 'wait', 'wake', 'way', 'whitby', 'wolf']
    N-grams removed: 329  (30 uni / 92 bi / 207 tri)

  TalesOfPoe
    Names matched : ['allan', 'art', 'auguste', 'belle', 'berenice', 'case', 'cat', 'cliff', 'davy', 'di', 'ebony', 'edgar', 'eleonora', 'fancy', 'fay', 'forest', 'gay', 'germain', 'gray', 'griswold', 'gusty', 'hope', 'humphrey', 'king', 'la', 'lay', 'love', 'madeline', 'marie', 'may', 'miles', 'nil', 'prince', 'puff', 'raven', 'red', 'rock', 'roderick', 'rog', 'ruby', 'saw', 'say', 'scarlet', 'see', 'shadow', 'si', 'thomas', 'valdemar', 'vale', 'von', 'way', 'west', 'william', 'wilson']
    N-grams removed: 147  (22 uni / 40 bi / 85 tri)

  DrJekyllAndMrHyde
    Names matched : ['bear', 'bell', 'butler', 'cain', 'case', 'drew', 'dusty', 'edward', 'else', 'fancy', 'forest', 'fortune', 'glad', 'grant', 'harry', 'henry', 'hope', 'ivy', 'jewel', 'lay', 'louis', 'love', 'mark', 'may', 'red', 'richard', 'robert', 'saw', 'say', 'see', 'storey', 'town', 'way', 'yard']
    N-grams removed: 173  (18 uni / 67 bi / 88 tri)

  PrideAndPrejudice
    Names matched : ['allen', 'austen', 'bear', 'bennet', 'carter', 'case', 'catherine', 'charles', 'charlotte', 'collins', 'darcy', 'denny', 'drew', 'eliza', 'elizabeth', 'else', 'forster', 'fortune', 'gardiner', 'george', 'glad', 'happy', 'hope', 'james', 'jane', 'king', 'kitty', 'lane', 'lewis', 'lizzy', 'love', 'lucas', 'lydia', 'marry', 'mary', 'may', 'miles', 'reynolds', 'saw', 'say', 'see', 'steward', 'town', 'wait', 'way', 'william']
    N-grams removed: 456  (33 uni / 146 bi / 277 tri)

  RomeoAndJuliet
    Names matched : ['abram', 'art', 'bear', 'bride', 'cam', 'carry', 'case', 'dew', 'else', 'er', 'eve', 'faith', 'flower', 'fortune', 'goose', 'gregory', 'hall', 'happy', 'hope', 'john', 'joy', 'jule', 'juliet', 'lark', 'lawrence', 'lay', 'love', 'mark', 'marry', 'may', 'merry', 'montague', 'noble', 'page', 'peter', 'prince', 'rich', 'romeo', 'rosaline', 'sampson', 'saw', 'say', 'see', 'son', 'star', 'susan', 'town', 'tybalt', 'vi', 'way', 'william', 'wilt', 'wit']
    N-grams removed: 447  (44 uni / 193 bi / 210 tri)

  JaneEyre
    Names matched : ['abbot', 'amy', 'ann', 'bear', 'bell', 'bessie', 'blanche', 'bride', 'briggs', 'carter', 'case', 'cat', 'charity', 'cherry', 'diana', 'drew', 'edward', 'eliza', 'elliott', 'else', 'fairfax', 'fancy', 'florence', 'fortune', 'french', 'george', 'georgiana', 'glad', 'grace', 'hall', 'hannah', 'happy', 'heath', 'helen', 'hope', 'ingram', 'jane', 'john', 'lane', 'lay', 'lloyd', 'louisa', 'love', 'lynn', 'marry', 'marsh', 'mary', 'mason', 'may', 'miles', 'morton', 'oliver', 'page', 'pearl', 'red', 'reed', 'ric', 'rich', 'rochester', 'rosamond', 'rose', 'saw', 'say', 'see', 'shell', 'sky', 'smith', 'storey', 'temple', 'town', 'vale', 'ward', 'way', 'west', 'wilson', 'wood']
    N-grams removed: 403  (38 uni / 115 bi / 250 tri)

  WutheringHeights
    Names matched : ['bear', 'catherine', 'cathy', 'dean', 'drew', 'edgar', 'ellen', 'else', 'emily', 'fancy', 'glad', 'hale', 'happy', 'heathcliff', 'hope', 'isabella', 'jabez', 'joseph', 'joy', 'kenneth', 'lay', 'lockwood', 'love', 'marry', 'may', 'miles', 'nelly', 'park', 'rose', 'saw', 'say', 'see', 'son', 'stormy', 'wait', 'way']
    N-grams removed: 227  (29 uni / 102 bi / 96 tri)

  SenseAndSensibility
    Names matched : ['austen', 'bartlett', 'barton', 'bear', 'berkeley', 'brandon', 'case', 'charlotte', 'cleveland', 'drew', 'edward', 'elinor', 'else', 'fancy', 'fanny', 'fortune', 'glad', 'gray', 'happy', 'harley', 'harris', 'henry', 'hope', 'jane', 'jennings', 'john', 'joy', 'love', 'lucy', 'magna', 'margaret', 'marianne', 'marry', 'may', 'merry', 'miles', 'morton', 'palmer', 'park', 'penny', 'red', 'robert', 'saw', 'say', 'see', 'smith', 'son', 'town', 'vi', 'wait', 'way', 'worth']
    N-grams removed: 408  (34 uni / 140 bi / 234 tri)

  OnTheTrailOfTheSpacePirates
    Names matched : ['brooks', 'chance', 'claude', 'crystal', 'gus', 'guy', 'hope', 'job', 'joe', 'lay', 'luna', 'luther', 'major', 'mike', 'miles', 'nicholas', 'pete', 'ray', 'rock', 'roger', 'rose', 'row', 'saw', 'say', 'scarlet', 'see', 'skipper', 'sky', 'star', 'steve', 'tom', 'venus', 'wait', 'wallace', 'way', 'worth']
    N-grams removed: 245  (26 uni / 104 bi / 115 tri)

  PlagueShip
    Names matched : ['ali', 'andre', 'andrew', 'bay', 'bill', 'cam', 'case', 'cat', 'chance', 'cinnamon', 'craig', 'dane', 'dee', 'drew', 'else', 'forest', 'fortune', 'frank', 'glad', 'gray', 'hall', 'happy', 'hope', 'hunt', 'job', 'lay', 'luna', 'may', 'norton', 'pace', 'ray', 'red', 'rich', 'rock', 'rod', 'ruby', 'saw', 'say', 'see', 'shadow', 'shannon', 'sky', 'star', 'storm', 'terra', 'van', 'wait', 'way', 'west', 'wood', 'worth']
    N-grams removed: 278  (31 uni / 132 bi / 115 tri)

  TheWarOfTheWorlds
    Names matched : ['bear', 'case', 'chance', 'dawn', 'drew', 'eve', 'george', 'henderson', 'hill', 'hope', 'john', 'kingston', 'lane', 'lay', 'mark', 'may', 'miles', 'park', 'ram', 'ray', 'red', 'richmond', 'rose', 'saw', 'say', 'see', 'serene', 'sky', 'star', 'storm', 'ulla', 'vi', 'way', 'wells', 'wood']
    N-grams removed: 178  (23 uni / 74 bi / 81 tri)

  TheTimeMachine
    Names matched : ['bell', 'case', 'drew', 'fancy', 'forest', 'gates', 'hall', 'hill', 'hope', 'ivory', 'lay', 'may', 'mayor', 'nil', 'red', 'rose', 'saw', 'say', 'see', 'shadow', 'simon', 'sky', 'trace', 'vi', 'wait', 'way', 'wells', 'wood']
    N-grams removed: 111  (22 uni / 41 bi / 48 tri)

  TwentyThousandLeagues
    Names matched : ['abraham', 'april', 'bab', 'bay', 'bear', 'case', 'chance', 'con', 'coral', 'forest', 'france', 'french', 'gunner', 'happy', 'hope', 'la', 'lay', 'lincoln', 'may', 'miles', 'ned', 'pearl', 'pierre', 'red', 'renaud', 'rock', 'rose', 'saw', 'say', 'see', 'shell', 'sky', 'steward', 'vi', 'way', 'west', 'wood', 'worthy']
    N-grams removed: 181  (23 uni / 57 bi / 101 tri)

Filtering complete — results dict updated.

In [79]:
# ── Removal documentation: show exactly which n-grams were dropped per book ──
for book in BOOKS:
    log = removal_log[book]
    genre = BOOKS[book]
    total = sum(len(log[k]) for k in ['unigrams', 'bigrams', 'trigrams'])

    print(f"\n{'='*60}")
    print(f"  {book}  [{genre.upper()}]  —  {total} n-gram(s) removed")
    print(f"{'='*60}")

    for ngram_type in ['unigrams', 'bigrams', 'trigrams']:
        items = log[ngram_type]
        if items:
            df = pd.DataFrame(items, columns=['ngram', 'count'])
            df.index += 1
            print(f"\n  Removed {ngram_type} ({len(items)}):")
            display(df)
        else:
            print(f"\n  No {ngram_type} removed.")

============================================================
  AutobiographyOfBenjaminFranklin  [BIOGRAPHY]  —  247 n-gram(s) removed
============================================================

  Removed unigrams (27):

       ngram  count
1   franklin    132
2        may    107
3        see     69
4        way     49
5        saw     37
6       town     34
7        son     31
8       king     30
9    william     29
10   richard     28
11    french     27
12      case     25
13      john     25
14     ralph     22
15     james     21
16      drew     20
17  benjamin     19
18   fortune     19
19       say     18
20  bradford     18
21    thomas     16
22    france     16
23     royal     16
24    george     15
25      page     14
26     carry     14
27     miles     14

  Removed bigrams (77):

                ngram  count
1        poor richard     25
2   benjamin franklin     11
3        richard says     11
4     richard almanac      9
5       royal society      7
..                ...    ...
73        court louis      2
74          louis xvi      2
75           put king      2
76         king prize      2
77      doctor thomas      2

[77 rows x 2 columns]

  Removed trigrams (143):

                      ngram  count
1         poor richard says     11
2      poor richard almanac      9
3     father abraham speech      4
4            first page new      3
5          page new england      3
..                      ...    ...
139     show front franklin      1
140     front franklin arms      1
141  franklin arms franklin      1
142      arms franklin seal      1
143      franklin seal back      1

[143 rows x 2 columns]

============================================================
  LifeOfKingEdwardVII  [BIOGRAPHY]  —  509 n-gram(s) removed
============================================================

  Removed unigrams (39):

        ngram  count
1      prince   1053
2       royal    748
3        king    659
4        duke    346
5      edward    222
6         may    220
7        earl    154
8      canada    132
9      george    128
10   victoria    127
11       june     92
12      mayor     85
13        way     84
14  alexandra     80
15       hall     73
16    william     68
17     albert     66
18     august     58
19    charles     57
20      henry     57
21       john     57
22      april     56
23        son     52
24     french     51
25        saw     48
26       love     46
27       town     46
28  frederick     44
29      major     42
30       hope     41
31        see     39
32        say     39
33     france     37
34      james     37
35       case     34
36        lev     32
37     arthur     31
38     bishop     31
39      abbey     31

  Removed bigrams (188):

                ngram  count
1        prince wales    262
2      royal highness    169
3         king edward    122
4     prince princess     80
5      queen victoria     60
..                ...    ...
184   duke devonshire      6
185  duke westminster      6
186         late duke      6
187     thomas lipton      6
188         time king      6

[188 rows x 2 columns]

  Removed trigrams (282):

                         ngram  count
1        prince princess wales     36
2         members royal family     28
3            major general sir     15
4              king edward vii     14
5         prince albert victor     14
..                         ...    ...
278  prince wales illustration      2
279        king louis philippe      2
280           richard coeur de      2
281              coeur de lion      2
282           reign henry viii      2

[282 rows x 2 columns]

============================================================
  NarrativeOfFrederickDouglass  [BIOGRAPHY]  —  192 n-gram(s) removed
============================================================

  Removed unigrams (36):

        ngram  count
1       lloyd     42
2         may     36
3         see     33
4         way     31
5         say     30
6       henry     23
7      thomas     23
8         saw     22
9   frederick     21
10   douglass     21
11    michael     21
12       hugh     21
13       hope     18
14       case     17
15      miles     17
16   hamilton     15
17        bay     14
18       love     13
19       john     13
20        lay     13
21    william     13
22       yard     13
23      noble     12
24    gardner     12
25       glad     11
26       bear     11
27     bailey     11
28       fred     10
29     easton      9
30        son      9
31       wood      9
32      sandy      9
33       else      8
34     talbot      8
35   lucretia      8
36        joy      8

  Removed bigrams (65):

                 ngram  count
1        colonel lloyd     36
2           st michael     21
3          master hugh     19
4        master thomas     14
5   frederick douglass     13
..                 ...    ...
61          master son      2
62             son law      2
63       see baltimore      2
64          lloyd kept      2
65            wye town      2

[65 rows x 2 columns]

  Removed trigrams (91):

                       ngram  count
1   colonel lloyd plantation      9
2     talbot county maryland      6
3       colonel lloyd slaves      6
4            mr gardner ship      4
5          gardner ship yard      4
..                       ...    ...
87    breaking rod oppressor      1
88     rod oppressor letting      1
89     befriend hazards love      1
90          hazards love god      1
91         love god humanity      1

[91 rows x 2 columns]

============================================================
  StoryOfMyLife  [BIOGRAPHY]  —  333 n-gram(s) removed
============================================================

  Removed unigrams (26):

        ngram  count
1       helen    538
2         see    300
3    sullivan    236
4        love    220
5         way    134
6       happy    132
7         may    111
8         say     93
9        glad     90
10       king     85
11        saw     73
12       hope     71
13    mildred     66
14       doll     61
15        joy     58
16     french     51
17       bell     44
18  radcliffe     34
19      nancy     33
20       june     29
21       else     29
22       john     28
23      laura     27
24     brooks     25
25       rose     24
26   sunshine     24

  Removed bigrams (122):

             ngram  count
1    miss sullivan    230
2     helen keller    115
3     friend helen     30
4        could see     28
5       frost king     28
..             ...    ...
118   people happy      5
119      love many      5
120    happy think      5
121     make happy      5
122       must say      5

[122 rows x 2 columns]

  Removed trigrams (185):

                         ngram  count
1          little friend helen     26
2          friend helen keller     24
3          mrs laurence hutton     18
4          miss caroline derby     11
5        alexander graham bell      9
..                         ...    ...
181    radcliffe college first      2
182  sullivan read examination      2
183           papers mr eugene      2
184           mr eugene vining      2
185          eugene vining one      2

[185 rows x 2 columns]

============================================================
  AutobiographyOfCharlesDarwin  [BIOGRAPHY]  —  140 n-gram(s) removed
============================================================

  Removed unigrams (16):

      ngram  count
1       may     28
2       saw     25
3       say     16
4      case     15
5       see     14
6       roy     11
7    darwin     10
8      fitz     10
9     worth      9
10    coral      9
11     love      8
12     bird      7
13  wallace      7
14     hope      6
15      way      6
16    royal      5

  Removed bigrams (44):

              ngram  count
1          fitz roy     10
2       coral reefs      7
3        mr wallace      5
4           mr case      4
5          asa gray      4
6     wallace essay      4
7    charles darwin      3
8            may th      3
9   josiah wedgwood      3
10        dr butler      3
11          saw two      3
12         dr grant      3
13    royal society      3
14     robert brown      3
15      written may      2
16           may st      2
17     uncle josiah      2
18     nothing else      2
19          may add      2
20        mr darwin      2
21    edinburgh saw      2
22    royal medical      2
23     thirty miles      2
24     king college      2
25       crux major      2
26     sir herschel      2
27   worth anything      2
28     love science      2
29       tierra del      2
30        del fuego      2
31       white rock      2
32      society saw      2
33      views coral      2
34         time saw      2
35         saw also      2
36      deal robert      2
37       work coral      2
38         saw good      2
39       little say      2
40        say worth      2
41     worth saying      2
42      may mention      2
43        may worth      2
44        miss bird      2

  Removed trigrams (80):

                          ngram  count
1               letter asa gray      3
2                written may st      2
3         uncle josiah wedgwood      2
4         royal medical society      2
5              tierra del fuego      2
..                          ...    ...
76  believe leighton afterwards      1
77   leighton afterwards became      1
78              never tried may      1
79               tried may also      1
80             may also confess      1

[80 rows x 2 columns]

============================================================
  TheWonderfulWizardOfOz  [FANTASY]  —  285 n-gram(s) removed
============================================================

  Removed unigrams (28):

      ngram  count
1   dorothy    369
2   woodman    183
3      lion    180
4       see     95
5       way     64
6       saw     58
7    forest     47
8     carry     28
9      west     26
10     king     25
11       em     25
12      lay     24
13      may     22
14     glad     19
15      say     16
16    gates     15
17     gray     15
18    happy     15
19    henry     13
20     hill     13
21     love     12
22     wood     11
23      sky     10
24      joy      9
25      red      9
26     wait      9
27     hope      9
28     rich      8

  Removed bigrams (114):

             ngram  count
1      tin woodman    118
2     said dorothy     44
3    asked dorothy     28
4          aunt em     24
5    cowardly lion     22
..             ...    ...
110     carry back      3
111       lost way      3
112    king winged      3
113     shall glad      3
114   good fortune      3

[114 rows x 2 columns]

  Removed trigrams (143):

                        ngram  count
1            said tin woodman     19
2       scarecrow tin woodman     15
3           wicked witch west     12
4          said cowardly lion      8
5                see great oz      6
..                        ...    ...
139  instinctive love stories      1
140    love stories fantastic      1
141    served generations may      1
142   generations may classed      1
143    may classed historical      1

[143 rows x 2 columns]

============================================================
  AliceInWonderland  [FANTASY]  —  275 n-gram(s) removed
============================================================

  Removed unigrams (18):

      ngram  count
1     alice    399
2       see     67
3      king     63
4       way     57
5       say     51
6       cat     37
7      bill     18
8       saw     14
9     dinah     14
10      may     13
11     else     12
12     glad     11
13      fan     10
14     hall      9
15  william      8
16     wood      8
17    fancy      7
18     lory      7

  Removed bigrams (109):

                 ngram  count
1           said alice    123
2            said king     29
3        thought alice     26
4           alice said     17
5             said cat     14
..                 ...    ...
105          right way      2
106  william conqueror      2
107           see dear      2
108        thing alice      2
109         alice time      2

[109 rows x 2 columns]

  Removed trigrams (148):

                    ngram  count
1    certainly said alice      5
2         know said alice      4
3          might well say      4
4         said alice said      4
5        beau ootiful soo      4
..                    ...    ...
144    thought alice fall      1
145      alice fall shall      1
146        think home say      1
147     home say anything      1
148     say anything even      1

[148 rows x 2 columns]

============================================================
  ThroughTheLookingGlass  [FANTASY]  —  351 n-gram(s) removed
============================================================

  Removed unigrams (26):

     ngram  count
1    alice    468
2      see     86
3      red     71
4     king     67
5      way     67
6      say     55
7     wood     30
8    kitty     25
9      may     21
10    lion     20
11    lily     18
12     saw     14
13    hill     14
14    hope     14
15    rose     13
16    else     12
17   brook     12
18   dinah     10
19    glad     10
20    wait      9
21    town      8
22    fawn      7
23    wake      7
24   daisy      6
25  forest      6
26    deny      6

  Removed bigrams (137):

             ngram  count
1       said alice     72
2        red queen     56
3       alice said     55
4    alice thought     20
5         said red     17
..             ...    ...
133     see garden      2
134       top hill      2
135  talking alice      2
136   hill minutes      2
137      lily said      2

[137 rows x 2 columns]

  Removed trigrams (188):

                   ngram  count
1         said red queen     15
2         red queen said      9
3        said tiger lily      5
4    alice said politely      5
5         said alice one      4
..                   ...    ...
184   story happy summer      1
185    happy summer days      1
186  vanish summer glory      1
187   summer glory shall      1
188    glory shall touch      1

[188 rows x 2 columns]

============================================================
  GrimmsFairyTales  [FANTASY]  —  276 n-gram(s) removed
============================================================

  Removed unigrams (43):

        ngram  count
1        king    368
2         saw    183
3         see    155
4         way    148
5        hans    125
6        bird    121
7         son    115
8      gretel     98
9         red     92
10        cat     89
11        fox     89
12     forest     85
13        may     83
14       wood     82
15        lay     82
16       wolf     72
17     tailor     69
18     prince     68
19      bride     56
20       rose     54
21        say     54
22     hansel     47
23       bear     45
24      carry     40
25       drew     36
26        tom     30
27      goose     29
28      elsie     29
29        joy     29
30       lion     28
31   shepherd     28
32      merry     27
33       wait     27
34  frederick     26
35      happy     25
36       town     23
37       rich     21
38      royal     21
39       else     21
40      raven     20
41     flower     20
42   gardener     19
43       glad     19

  Removed bigrams (95):

            ngram  count
1   little tailor     33
2   king daughter     30
3         red cap     29
4        king son     29
5       king said     22
..            ...    ...
91      came king      5
92    king twelve      5
93     king asked      5
94      king land      5
95    king looked      5

[95 rows x 2 columns]

  Removed trigrams (138):

                   ngram  count
1         little red cap     17
2        gretel good day     12
3      goodbye hans hans     11
4      king grisly beard     10
5        snow white rose      8
..                   ...    ...
134  said fisherman king      2
135        yes said king      2
136       said wolf must      2
137     willow wren sent      2
138     could see bottom      2

[138 rows x 2 columns]

============================================================
  GulliversTravels  [FANTASY]  —  94 n-gram(s) removed
============================================================

  Removed unigrams (17):

      ngram  count
1      king     99
2       see     80
3       may     72
4       saw     71
5    prince     52
6       way     50
7       lay     50
8      town     40
9     royal     34
10      say     33
11  fortune     30
12    carry     30
13    miles     29
14     hope     22
15    noble     21
16     west     20
17     love     20

  Removed bigrams (27):

             ngram  count
1     good fortune     13
2        could see     12
3       reader may     11
4       king queen      9
5       north west      8
6     love country      7
7       south west      7
8       lay ground      5
9       royal port      5
10      way living      5
11        th april      5
12       say truth      5
13   curiosity see      4
14      may appear      4
15      chapter vi      4
16    royal palace      4
17     great storm      4
18        day june      4
19       good hope      4
20     drew hanger      4
21    twenty miles      4
22  thousand miles      4
23     desired see      4
24   king luggnagg      4
25       could way      3
26      see author      3
27      people see      3

  Removed trigrams (50):

                      ngram  count
1            cape good hope      4
2               th day june      3
3           van diemen land      2
4         could see nothing      2
5             pen ink paper      2
6           every thing saw      2
7       access royal person      2
8         reader may please      2
9        may please observe      2
10      largest trees royal      2
11         trees royal park      2
12       blefuscu sue peace      2
13    royal person resolved      2
14      reader may remember      2
15    luckiest chance world      2
16      royal port blefuscu      2
17    captain john nicholas      2
18          west south west      2
19          north west part      2
20       twenty miles house      2
21      attended king queen      2
22           near place lay      2
23         say upon subject      2
24            th day august      2
25        ever good fortune      2
26      saw nothing country      2
27               th day may      2
28          pedro de mendez      2
29   nations world jonathan      1
30     world jonathan swift      1
31      jonathan swift dean      1
32            swift dean st      1
33          dean st patrick      1
34        st patrick dublin      1
35     patrick dublin first      1
36        travels mr lemuel      1
37       mr lemuel gulliver      1
38  lemuel gulliver ancient      1
39            yet heard say      1
40         heard say family      1
41          say family came      1
42       affirmed thing say      1
43           thing say true      1
44              say true mr      1
45    advice several worthy      1
46   several worthy persons      1
47    worthy persons author      1
48         world hoping may      1
49         hoping may least      1
50           may least time      1

============================================================
  Frankenstein  [HORROR]  —  133 n-gram(s) removed
============================================================

  Removed unigrams (23):

        ngram  count
1         may     99
2         saw     94
3   elizabeth     92
4        love     59
5     justine     55
6         see     50
7        hope     50
8       felix     50
9       happy     46
10        joy     42
11     geneva     36
12        lay     28
13     victor     28
14       town     26
15      henry     26
16       wood     26
17    william     25
18        say     23
19     agatha     22
20       drew     20
21        son     19
22        way     18
23       rose     16

  Removed bigrams (50):

                ngram  count
1         dear victor     10
2            de lacey      9
3     william justine      7
4           never saw      6
5   cornelius agrippa      6
6         native town      6
7        poor william      6
8           first saw      6
9      dearest victor      5
10          august th      4
11         every hope      4
12         may easily      4
13          drew near      4
14        drew nearer      4
15     justine moritz      4
16       poor justine      4
17           gave way      4
18   elizabeth father      4
19      dear margaret      3
20  elizabeth lavenza      3
21      henry clerval      3
22    albertus magnus      3
23      return geneva      3
24     sincerely love      3
25             may th      3
26     elizabeth also      3
27           mont sal      3
28   justine innocent      3
29     said elizabeth      3
30         make happy      3
31         around saw      3
32           sun rose      3
33         saw change      3
34           saw boat      3
35       may expected      2
36       may remember      2
37       uncle thomas      2
38      walton letter      2
39   moderate fortune      2
40          may never      2
41        perhaps may      2
42      love tenderly      2
43         see native      2
44      hundred miles      2
45       saw equalled      2
46     noble creature      2
47  caroline beaufort      2
48     guardian angel      2
49       bounding joy      2
50     schools geneva      2

  Removed trigrams (60):

                             ngram  count
1                walton letter mrs      2
2               never saw equalled      2
3       albertus magnus paracelsus      2
4                  drew near close      2
5              hope sincerely hope      2
6         elizabeth lavenza geneva      2
7                    geneva may th      2
8                   every one else      2
9              felix bestowed upon      2
10               looked around saw      2
11                 de lacey agatha      2
12                    old de lacey      2
13         william justine clerval      2
14          modern prometheus mary      1
15  prometheus mary wollstonecraft      1
16      mary wollstonecraft godwin      1
17   wollstonecraft godwin shelley      1
18         godwin shelley contents      1
19         shelley contents letter      1
20         beauty delight margaret      1
21            delight margaret sun      1
22               margaret sun ever      1
23                    calm sea may      1
24                  sea may wafted      1
25                 may wafted land      1
26        productions features may      1
27            features may without      1
28             may without example      1
29      undiscovered solitudes may      1
30          solitudes may expected      1
31            may expected country      1
32               eternal light may      1
33              light may discover      1
34           may discover wondrous      1
35             attracts needle may      1
36             needle may regulate      1
37           may regulate thousand      1
38               never visited may      1
39               visited may tread      1
40                  may tread land      1
41            laborious voyage joy      1
42                voyage joy child      1
43                 joy child feels      1
44                  point soul may      1
45                    soul may fix      1
46            may fix intellectual      1
47               surround pole may      1
48               pole may remember      1
49            may remember history      1
50               good uncle thomas      1
51            uncle thomas library      1
52        thomas library education      1
53             obtain niche temple      1
54              niche temple names      1
55              temple names homer      1
56         names homer shakespeare      1
57   homer shakespeare consecrated      1
58          time inherited fortune      1
59        inherited fortune cousin      1
60         fortune cousin thoughts      1

============================================================
  CallOfCthulu  [HORROR]  —  113 n-gram(s) removed
============================================================

  Removed unigrams (21):

     ngram  count
1    april     12
2      may     10
3      way      9
4     emma      9
5      saw      8
6     webb      7
7      see      7
8    storm      7
9      lay      6
10  sydney      6
11     sky      5
12    rock      5
13    clay      4
14    case      4
15    west      4
16     tom      4
17    trip      4
18    else      3
19    hill      3
20   fancy      3
21     art      3

  Removed bigrams (43):

                 ngram  count
1             april nd      6
2       professor webb      5
3          storm april      3
4             clay bas      2
5          fancy could      2
6          alone fleur      2
7             fleur de      2
8             dr tobey      2
9             one case      2
10            th april      2
11            tom toms      2
12           world sky      2
13     sydney bulletin      2
14            april th      2
15     gustaf johansen      2
16        capt collins      2
17            emma men      2
18           emma crew      2
19          beings may      1
20     may conceivably      1
21      kinds algernon      1
22  algernon blackwood      1
23        late francis      1
24     francis wayland      1
25    wayland thurston      1
26     thurston boston      1
27         horror clay      1
28       clay merciful      1
29         things case      1
30            case old      1
31      professor hope      1
32            hope one      1
33            one else      1
34     else accomplish      1
35        uncle george      1
36      george gammell      1
37             two may      1
38        may recalled      1
39          steep hill      1
40        hill elderly      1
41            time saw      1
42          saw reason      1
43          queer clay      1

  Removed trigrams (49):

                              ngram  count
1                    storm april nd      3
2                   clay bas relief      2
3                    alone fleur de      2
4                      fleur de lys      2
5                 powers beings may      1
6            beings may conceivably      1
7          may conceivably survival      1
8              sorts kinds algernon      1
9          kinds algernon blackwood      1
10  algernon blackwood illustration      1
11              papers late francis      1
12             late francis wayland      1
13         francis wayland thurston      1
14          wayland thurston boston      1
15           thurston boston horror      1
16               boston horror clay      1
17             horror clay merciful      1
18              clay merciful thing      1
19            separated things case      1
20                  things case old      1
21               case old newspaper      1
22              dead professor hope      1
23               professor hope one      1
24                    hope one else      1
25              one else accomplish      1
26          else accomplish piecing      1
27               grand uncle george      1
28             uncle george gammell      1
29            george gammell angell      1
30                   ninety two may      1
31                 two may recalled      1
32                may recalled many      1
33                ascent steep hill      1
34               steep hill elderly      1
35                 hill elderly man      1
36                     end time saw      1
37                  time saw reason      1
38               saw reason dissent      1
39               meaning queer clay      1
40                   queer clay bas      1
41                 uncle failed way      1
42              failed way identify      1
43          way identify particular      1
44              form diseased fancy      1
45             diseased fancy could      1
46             fancy could conceive      1
47               could conceive say      1
48            conceive say somewhat      1
49         say somewhat extravagant      1

============================================================
  Dracula  [HORROR]  —  329 n-gram(s) removed
============================================================

  Removed unigrams (30):

       ngram  count
1        may    419
2        see    395
3        van    323
4       lucy    301
5       mina    244
6        way    229
7        saw    219
8   jonathan    208
9        say    148
10    arthur    147
11   quincey     85
12      love     84
13    morris     78
14      john     76
15       red     74
16       lay     73
17      case     72
18      hope     66
19     happy     48
20      wait     45
21    whitby     43
22      rose     40
23    chance     40
24      drew     39
25      glad     36
26      wake     34
27    august     32
28      hall     32
29      else     30
30      wolf     28

  Removed bigrams (92):

            ngram  count
1     van helsing    323
2       could see    103
3      madam mina     87
4          dr van     67
5     friend john     59
..            ...    ...
88  sister agatha      5
89       want see      5
90    lucy mother      5
91    helsing saw      5
92       went see      5

[92 rows x 2 columns]

  Removed trigrams (207):

                       ngram  count
1             dr van helsing     67
2            dear madam mina     24
3    jonathan harker journal     23
4           van helsing said     22
5           said van helsing     19
..                       ...    ...
203        clock van helsing      2
204   lucy westenra unopened      2
205   september dearest lucy      2
206           mina harker dr      2
207          lucy face could      2

[207 rows x 2 columns]

============================================================
  TalesOfPoe  [HORROR]  —  147 n-gram(s) removed
============================================================

  Removed unigrams (22):

       ngram  count
1        say    102
2        may     86
3        lay     68
4        saw     67
5        see     61
6        way     55
7       king     40
8       case     32
9        red     31
10  valdemar     29
11     fancy     29
12       art     28
13      hope     27
14      rock     25
15    shadow     25
16    wilson     24
17      love     23
18     miles     21
19       von     18
20      gray     18
21       cat     17
22  berenice     16

  Removed bigrams (40):

               ngram  count
1          said king     21
2       von kempelen     17
3          could see      9
4           made way      9
5          upon rock      8
6     william wilson      8
7          black cat      7
8          red death      7
9           lay upon      7
10   prince prospero      6
11          may well      5
12     lady madeline      5
13         puff puff      4
14         lay close      4
15     case valdemar      3
16        island fay      3
17           say one      3
18         blood red      3
19           red hot      3
20      little cliff      3
21    impossible say      3
22      sir humphrey      3
23     humphrey davy      3
24           god say      3
25    roderick usher      3
26       ebony clock      3
27        sir thomas      3
28          art thou      3
29      may possibly      3
30          may seem      3
31         west wing      3
32          ruby red      3
33  petrified forest      3
34       forest near      3
35       edgar allan      2
36         allan poe      2
37        facts case      2
38        masque red      2
39    heart berenice      2
40    eleonora notes      2

  Removed trigrams (85):

                        ngram  count
1               sat upon rock      5
2      von kempelen discovery      4
3               hum said king      4
4            lay close within      4
5           sir humphrey davy      3
..                        ...    ...
81            rog looked upon      1
82  nothing assassination way      1
83     assassination way hope      1
84                way hope oh      1
85            hope oh nothing      1

[85 rows x 2 columns]

============================================================
  DrJekyllAndMrHyde  [HORROR]  —  173 n-gram(s) removed
============================================================

  Removed unigrams (18):

     ngram  count
1      see     47
2      way     32
3    henry     30
4      say     25
5   edward     25
6      saw     24
7      may     22
8     case     16
9      lay     16
10    drew     13
11  butler     12
12     red      8
13    hope      7
14    bear      6
15    else      5
16   harry      5
17   fancy      5
18    yard      5

  Removed bigrams (67):

                 ngram  count
1         henry jekyll     30
2          edward hyde     25
3            could see      4
4              say sir      4
5            never saw      3
..                 ...    ...
63        say quaintly      1
64           devil way      1
65       way character      1
66  frequently fortune      1
67        fortune last      1

[67 rows x 2 columns]

  Removed trigrams (88):

                     ngram  count
1           case dr jekyll      2
2        carew murder case      2
3        henry jekyll full      2
4      full statement case      2
5            never saw man      2
..                     ...    ...
84         morning way lay      1
85            way lay part      1
86           lay part town      1
87     part town literally      1
88  town literally nothing      1

[88 rows x 2 columns]

============================================================
  PrideAndPrejudice  [ROMANCE]  —  456 n-gram(s) removed
============================================================

  Removed unigrams (33):

        ngram  count
1   elizabeth    645
2       darcy    432
3      bennet    339
4        jane    302
5         may    206
6     collins    190
7       lydia    176
8         say    160
9         see    153
10  catherine    132
11       hope    125
12        way    115
13       love    102
14        saw    102
15      lizzy     97
16   gardiner     97
17  charlotte     87
18      happy     83
19      kitty     72
20      lucas     71
21       town     68
22     george     47
23      marry     46
24    william     46
25       mary     43
26       else     43
27    fortune     39
28    forster     39
29      allen     37
30       glad     36
31       case     35
32     austen     28
33       bear     25

  Removed bigrams (146):

                ngram  count
1            mr darcy    277
2          mr collins    160
3          mrs bennet    160
4      lady catherine    122
5           mr bennet     92
..                ...    ...
142  bennet daughters      4
143    elizabeth took      4
144      elizabeth mr      4
145        darcy took      4
146       darcy never      4

[146 rows x 2 columns]

  Removed trigrams (277):

                      ngram  count
1    copyright george allen     35
2         lady catherine de     15
3       catherine de bourgh     15
4           said mrs bennet     14
5      george allen chapter     13
..                      ...    ...
273  console lady catherine      2
274      miss bennet seemed      2
275        mrs collins glad      2
276         soon mrs bennet      2
277     may easily believed      2

[277 rows x 2 columns]

============================================================
  RomeoAndJuliet  [ROMANCE]  —  447 n-gram(s) removed
============================================================

  Removed unigrams (44):

       ngram  count
1      romeo    316
2     juliet    190
3       love    151
4   lawrence     82
5     tybalt     80
6        art     55
7        say     55
8        may     48
9   montague     47
10    prince     43
11       see     37
12      wilt     30
13     peter     29
14        er     26
15   sampson     22
16     marry     22
17       son     19
18   gregory     19
19     faith     18
20       joy     14
21      else     13
22       wit     13
23      page     12
24      bear     12
25     happy     12
26       lay     11
27      john     10
28       saw     10
29      rich     10
30  rosaline     10
31    flower     10
32      case      9
33       way      9
34   fortune      9
35      hall      8
36     noble      8
37     merry      8
38     goose      8
39     abram      7
40      mark      7
41     bride      6
42      lark      6
43      town      5
44       dew      5

  Removed bigrams (193):

              ngram  count
1    friar lawrence     78
2          thou art     28
3          art thou     23
4         thou wilt     21
5     lawrence cell     15
..              ...    ...
189       love give      2
190        ho romeo      2
191       romeo nay      2
192         may one      2
193      romeo fear      2

[193 rows x 2 columns]

  Removed trigrams (210):

                    ngram  count
1     friar lawrence cell     12
2      hall capulet house      6
3    enter friar lawrence      6
4     enter juliet juliet      5
5     lawrence cell enter      5
..                    ...    ...
206    therefore thou art      1
207        thou art moved      1
208        art moved thou      1
209       st away sampson      1
210      away sampson dog      1

[210 rows x 2 columns]

============================================================
  JaneEyre  [ROMANCE]  —  403 n-gram(s) removed
============================================================

  Removed unigrams (38):

        ngram  count
1   rochester    366
2        jane    346
3         see    276
4        john    202
5         say    200
6         saw    187
7        love    153
8         way    148
9         may    146
10    fairfax    137
11     bessie    131
12       reed    129
13       hall    105
14       rose     96
15       mary     96
16     ingram     90
17      diana     76
18       hope     75
19        lay     69
20     temple     65
21      helen     63
22      mason     61
23      happy     54
24      grace     49
25      marry     49
26       glad     44
27  georgiana     44
28       drew     44
29        sky     43
30       bear     42
31     french     41
32       wood     40
33     hannah     40
34       bell     36
35       case     35
36    fortune     35
37        red     33
38       rich     33

  Removed bigrams (115):

            ngram  count
1    mr rochester    332
2         st john    133
3     mrs fairfax    121
4        mrs reed     81
5     miss temple     63
..            ...    ...
111    truly love      4
112    jane think      4
113     jane know      4
114      blue sky      4
115      mary ann      4

[115 rows x 2 columns]

  Removed trigrams (250):

                       ngram  count
1                 mr st john     23
2          said mr rochester     13
3           see mr rochester      9
4           said mrs fairfax      8
5            mr rochester mr      8
..                       ...    ...
246           course st john      2
247             st john till      2
248              way st john      2
249            jane leave go      2
250  marry adhere resolution      2

[250 rows x 2 columns]

============================================================
  WutheringHeights  [ROMANCE]  —  227 n-gram(s) removed
============================================================

  Removed unigrams (29):

         ngram  count
1   heathcliff    476
2    catherine    382
3          see    174
4       joseph    140
5        cathy    124
6        edgar    116
7          may    110
8          say    107
9        ellen     99
10        love     90
11       nelly     89
12         saw     80
13         way     79
14    isabella     63
15        dean     49
16        else     47
17         lay     42
18        bear     42
19        hope     41
20         son     41
21        rose     34
22        glad     32
23        drew     31
24       happy     28
25        wait     25
26       fancy     25
27         joy     25
28     kenneth     24
29        park     23

  Removed bigrams (102):

                   ngram  count
1          mr heathcliff    130
2             miss cathy     38
3               mrs dean     37
4         miss catherine     31
5         mrs heathcliff     25
..                   ...    ...
98            would love      3
99             know love      3
100      heathcliff come      3
101         marry linton      3
102  whispered catherine      3

[102 rows x 2 columns]

  Removed trigrams (96):

                    ngram  count
1      mr heathcliff said      6
2     asked mr heathcliff      4
3         done miss cathy      3
4   heathcliff last night      3
5   heathcliff would soon      3
..                    ...    ...
92          one may guess      1
93        may guess power      1
94          limbs one way      1
95        one way craving      1
96       way craving alms      1

[96 rows x 2 columns]

============================================================
  SenseAndSensibility  [ROMANCE]  —  408 n-gram(s) removed
============================================================

  Removed unigrams (34):

        ngram  count
1      elinor    685
2    marianne    566
3      edward    263
4    jennings    235
5        lucy    186
6         may    175
7         see    173
8        john    164
9         say    160
10    brandon    144
11        saw    114
12      happy    100
13     barton     89
14       hope     88
15       town     86
16       love     77
17     palmer     77
18        way     74
19       park     52
20      fanny     48
21       else     46
22       glad     44
23    fortune     38
24     robert     37
25   margaret     36
26       case     36
27        son     35
28      fancy     31
29      marry     29
30  cleveland     27
31        joy     24
32  charlotte     24
33      worth     23
34       bear     23

  Removed bigrams (140):

               ngram  count
1       mrs jennings    234
2    colonel brandon    132
3           sir john    112
4        said elinor     65
5         mrs palmer     38
..               ...    ...
136         know may      4
137      even elinor      4
138   elinor without      4
139         ever see      4
140   marianne cried      4

[140 rows x 2 columns]

  Removed trigrams (234):

                       ngram  count
1          mrs john dashwood     25
2          said mrs jennings     15
3         cried mrs jennings      8
4              said sir john      7
5         sir john middleton      6
..                       ...    ...
230     jane austen contents      1
231  austen contents chapter      1
232       chapter chapter vi      1
233       chapter vi chapter      1
234           vi chapter vii      1

[234 rows x 2 columns]

============================================================
  OnTheTrailOfTheSpacePirates  [SCI-FI]  —  245 n-gram(s) removed
============================================================

  Removed unigrams (26):

      ngram  count
1       tom    512
2     roger    305
3   wallace    156
4       see     76
5       saw     60
6     steve     48
7       way     45
8       ray     40
9   skipper     37
10      say     36
11    major     30
12   chance     27
13      job     25
14   brooks     25
15     pete     23
16      gus     21
17     rock     20
18    venus     19
19     mike     18
20     hope     17
21     wait     16
22     luna     15
23      lay     14
24      guy     12
25      sky     12
26     star     12

  Removed bigrams (104):

              ngram  count
1          said tom     49
2     wallace simms     48
3       roger astro     37
4        paralo ray     36
5         tom roger     26
..              ...    ...
100    wallace said      3
101       roger get      3
102  roger followed      3
103    chimed roger      3
104     cruiser tom      3

[104 rows x 2 columns]

  Removed trigrams (115):

                    ngram  count
1          paralo ray gun     17
2            sir said tom     14
3           sir asked tom     11
4         tom roger astro     11
5       sir replied roger      8
..                    ...    ...
111       many miles away      2
112      saw blip outline      2
113          tom jet boat      2
114  roger voice crackled      2
115  roger replied strong      2

[115 rows x 2 columns]

============================================================
  PlagueShip  [SCI-FI]  —  278 n-gram(s) removed
============================================================

  Removed unigrams (31):

      ngram  count
1      dane    534
2       ali    182
3       van    144
4       way     73
5       see     69
6       saw     36
7     terra     35
8       cat     33
9       red     32
10   chance     27
11     wood     27
12  shannon     24
13      cam     24
14    storm     23
15      lay     21
16     hope     21
17     star     20
18      may     20
19   forest     18
20      say     17
21    frank     15
22     wait     15
23     rock     15
24      rod     14
25      job     14
26     gray     13
27     case     13
28     hunt     13
29     hall     13
30     luna     13
31     drew     12

  Removed bigrams (132):

              ngram  count
1         van rycke    115
2        dane could     15
3         could see     14
4     storm priests     14
5         dane knew     13
..              ...    ...
128     dane waited      2
129   shadow shield      2
130       wait upon      2
131  quickened pace      2
132        ali eyes      2

[132 rows x 2 columns]

  Removed trigrams (115):

                   ngram  count
1         dane could see      5
2        van rycke cargo      4
3       behind van rycke      3
4          saw van rycke      3
5      jellico van rycke      3
..                   ...    ...
111  grass forest beyond      1
112   forest beyond take      1
113  flowing carpet west      1
114     carpet west seas      1
115  west seas stretches      1

[115 rows x 2 columns]

============================================================
  TheWarOfTheWorlds  [SCI-FI]  —  178 n-gram(s) removed
============================================================

  Removed unigrams (23):

        ngram  count
1         saw    131
2         way    100
3         red     73
4         see     70
5        hill     60
6         lay     49
7         sky     47
8         may     43
9         ray     39
10       rose     32
11       ulla     28
12       lane     26
13     chance     23
14       park     22
15      miles     20
16       dawn     18
17        say     17
18       star     15
19  henderson     15
20       case     15
21   richmond     15
22       wood     13
23      storm     12

  Removed bigrams (74):

            ngram  count
1        heat ray     37
2        red weed     26
3       could see     24
4       ulla ulla     21
5    maybury hill      8
..            ...    ...
70  shooting star      2
71     rose early      2
72      soon dawn      2
73     black mark      2
74      saw black      2

[74 rows x 2 columns]

  Removed trigrams (81):

                    ngram  count
1          ulla ulla ulla     14
2            st john wood      5
3          st george hill      5
4           deep blue sky      3
5         top putney hill      3
..                    ...    ...
77  miles sunward morning      1
78   sunward morning star      1
79      morning star hope      1
80       star hope warmer      1
81     hope warmer planet      1

[81 rows x 2 columns]

============================================================
  TheTimeMachine  [SCI-FI]  —  111 n-gram(s) removed
============================================================

  Removed unigrams (22):

     ngram  count
1      saw     88
2      see     45
3      way     38
4      may     33
5      sky     33
6      red     26
7      say     20
8     hill     20
9      lay     16
10    wood     15
11    rose     13
12    hall     13
13   wells      9
14  forest      8
15   trace      7
16    hope      7
17    case      7
18  shadow      7
19   fancy      7
20    wait      6
21   ivory      6
22    drew      6

  Removed bigrams (41):

               ngram  count
1          could see     15
2         great hall      5
3   provincial mayor      4
4          round saw      3
5         across sky      3
6          saw white      3
7         saw little      3
8           may seem      3
9        fancied saw      3
10        little way      3
11         saw black      3
12         vi sunset      2
13           one may      2
14          see said      2
15        cannot see      2
16          see time      2
17           led way      2
18         rang bell      2
19         saw first      2
20       feeling way      2
21         way among      2
22          dare say      2
23          away saw      2
24     shoulder rose      2
25         see could      2
26        bright red      2
27         saw heads      2
28       dining hall      2
29          lay like      2
30          may even      2
31        hill crest      2
32          face saw      2
33       perhaps may      2
34       feeling may      2
35          lay path      2
36         came hill      2
37       eastern sky      2
38          wall saw      2
39      bronze gates      2
40          well saw      2
41         saw three      2

  Removed trigrams (48):

                          ngram  count
1             vi sunset mankind      2
2             looking round saw      2
3                 old moon rose      2
4            smell burning wood      2
5       machine invention wells      1
6      invention wells contents      1
7   wells contents introduction      1
8                 golden age vi      1
9                 age vi sunset      1
10                   put us way      1
11               us way marking      1
12           way marking points      1
13     argumentative person red      1
14              person red hair      1
15                red hair mean      1
16           line thickness nil      1
17           thickness nil real      1
18           nil real existence      1
19               solid body may      1
20               body may exist      1
21               may exist real      1
22            people think wait      1
23            think wait moment      1
24    wait moment instantaneous      1
25             mean another way      1
26          another way looking      1
27             way looking time      1
28               idea heard say      1
29             heard say fourth      1
30         say fourth dimension      1
31        said provincial mayor      1
32      provincial mayor simply      1
33           mayor simply space      1
34           dimensions one may      1
35                 one may call      1
36              may call length      1
37     geometry professor simon      1
38      professor simon newcomb      1
39     simon newcomb expounding      1
40        perspective thing see      1
41              thing see think      1
42           see think murmured      1
43    murmured provincial mayor      1
44    provincial mayor knitting      1
45         mayor knitting brows      1
46                yes think see      1
47               think see said      1
48                see said time      1

============================================================
  TwentyThousandLeagues  [SCI-FI]  —  181 n-gram(s) removed
============================================================

  Removed unigrams (23):

      ngram  count
1       ned    324
2       see    151
3       saw    125
4     miles    109
5       say     76
6       may     72
7      rose     54
8       red     52
9   abraham     46
10  lincoln     46
11    coral     41
12      way     41
13   chance     29
14     west     27
15     rock     27
16      lay     27
17     hope     26
18      bay     25
19   french     25
20   france     25
21   forest     23
22     case     23
23    shell     23

  Removed bigrams (57):

               ngram  count
1           ned land    196
2    abraham lincoln     46
3           said ned     31
4            red sea     26
5          could see     24
6         friend ned     22
7         miles hour     18
8        ned conseil     17
9        replied ned     14
10         two miles     14
11        la perouse     12
12          ned said     11
13        five miles     10
14      twenty miles     10
15          vigo bay      9
16          th april      8
17        north west      8
18         shall see      8
19     exclaimed ned      7
20         could say      7
21            th may      7
22         good hope      7
23       saw nothing      6
24          well ned      6
25         cried ned      6
26       see captain      6
27         six miles      6
28       saw captain      6
29     hundred miles      5
30     fifteen miles      5
31       miles south      5
32          ned well      5
33          must say      5
34       three miles      5
35     worthy fellow      5
36         might say      5
37        master ned      5
38       conseil ned      5
39            us see      5
40       see nothing      5
41    coral cemetery      5
42    miles nautilus      5
43      may nautilus      5
44        chapter vi      4
45  submarine forest      4
46         ten miles      4
47         brave ned      4
48      thirty miles      4
49     miles leeward      4
50     bear pressure      4
51    miles windward      4
52        made miles      4
53          miles us      4
54        opened saw      4
55          must see      4
56         asked ned      4
57         still see      4

  Removed trigrams (101):

                     ngram  count
1            said ned land     19
2         ned land conseil     15
3         replied ned land     11
4             sir said ned      7
5           cape good hope      7
..                     ...    ...
97        ned land carried      2
98          good hope cape      2
99          ned land would      2
100      platform ned land      2
101  man understand french      2

[101 rows x 2 columns]

## Display Results per Book

In [80]:
def show_book(book_name):
    """Pretty-print the top n-grams for a single book."""
    data = results[book_name]
    print(f"\n{'='*60}")
    print(f"  {book_name}  [{data['genre'].upper()}]")
    print(f"{'='*60}")

    for label, key in [("TOP 100 UNIGRAMS", 'unigrams'),
                       ("TOP 100 BIGRAMS",  'bigrams'),
                       ("TOP 100 TRIGRAMS", 'trigrams')]:
        print(f"\n--- {label} ---")
        df = pd.DataFrame(data[key], columns=['ngram', 'count'])
        df.index += 1
        display(df)

# Show all books
for book in BOOKS:
    show_book(book)

============================================================
  AutobiographyOfBenjaminFranklin  [BIOGRAPHY]
============================================================

--- TOP 100 UNIGRAMS ---

        ngram  count
1         one    294
2        time    201
3       would    199
4       great    174
5        good    160
..        ...    ...
469      side     14
470  happened     14
471    attend     14
472     terms     14
473     types     14

[473 rows x 2 columns]

--- TOP 100 BIGRAMS ---

               ngram  count
1           new york     38
2     printing house     28
3        new england     20
4          good deal     18
5    thousand pounds     18
..               ...    ...
419          ah says      2
420        says take      2
421       take kings      2
422    kings america      2
423      said doctor      2

[423 rows x 2 columns]

--- TOP 100 TRIGRAMS ---

                    ngram  count
1     new england courant      7
2     new printing office      5
3    printing office near      4
4       albany plan union      3
5     papers thro streets      3
..                    ...    ...
353       end papers show      1
354     papers show front      1
355       seal back medal      1
356      back medal given      1
357   public schools fund      1

[357 rows x 2 columns]

============================================================
  LifeOfKingEdwardVII  [BIOGRAPHY]
============================================================

--- TOP 100 UNIGRAMS ---

       ngram  count
1       lord    508
2        sir    460
3         th    453
4      great    423
5      queen    375
..       ...    ...
457  carried     30
458   russia     30
459    lords     30
460  journey     30
461  flowers     30

[461 rows x 2 columns]

--- TOP 100 BIGRAMS ---

                 ngram  count
1       princess wales     73
2        following day     72
3        heir apparent     63
4        great britain     50
5     government house     46
..                 ...    ...
308     indian princes      6
309         lord esher      6
310  duchess connaught      6
311         every kind      6
312        hicks beach      6

[312 rows x 2 columns]

--- TOP 100 TRIGRAMS ---

                           ngram  count
1              south african war     13
2           foundation stone new     10
3          great britain ireland      9
4          dominions beyond seas      9
5             state dinner given      9
..                           ...    ...
214           chapter xxviii new      2
215  beginning twentieth century      2
216            suez canal shares      2
217           canal shares order      2
218  evolution rather revolution      2

[218 rows x 2 columns]

============================================================
  NarrativeOfFrederickDouglass  [BIOGRAPHY]
============================================================

--- TOP 100 UNIGRAMS ---

      ngram  count
1       one    183
2     would    181
3        mr    177
4     slave    148
5    master    140
..      ...    ...
460  coming      8
461    sing      8
462    boys      8
463   spoke      8
464  ground      8

[464 rows x 2 columns]

--- TOP 100 BIGRAMS ---

               ngram  count
1           mr covey     47
2        new bedford     19
3         old master     15
4           run away     14
5            mr gore     14
..               ...    ...
431     leaving home      2
432       home would      2
433       would sing      2
434  following words      2
435      could slave      2

[435 rows x 2 columns]

--- TOP 100 TRIGRAMS ---

                            ngram  count
1                great house farm      9
2               would marked thus      6
3                woe unto scribes      4
4          unto scribes pharisees      4
5    scribes pharisees hypocrites      4
..                            ...    ...
405            voice people terms      1
406            people terms slave      1
407              terms slave code      1
408              slave code piece      1
409           code piece property      1

[409 rows x 2 columns]

============================================================
  StoryOfMyLife  [BIOGRAPHY]
============================================================

--- TOP 100 UNIGRAMS ---

         ngram  count
1       little    612
2          one    562
3         miss    447
4         many    326
5        would    326
..         ...    ...
470  following     24
471      print     24
472    realize     24
473       meet     24
474    visited     24

[474 rows x 2 columns]

--- TOP 100 BIGRAMS ---

                   ngram  count
1            miss keller    113
2             mr anagnos     74
3                one day     45
4            little girl     44
5    perkins institution     43
..                   ...    ...
374           would make      5
375          world would      5
376           would much      5
377          much better      5
378       keller teacher      5

[378 rows x 2 columns]

--- TOP 100 TRIGRAMS ---

                               ngram  count
1                 little blind girls     13
2                   miss canby story     10
3             little lord fauntleroy      9
4                  great round world      8
5                  south boston mass      8
..                               ...    ...
311            examination papers mr      2
312           vining one instructors      2
313          one instructors perkins      2
314  instructors perkins institution      2
315       institution blind employed      2

[315 rows x 2 columns]

============================================================
  AutobiographyOfCharlesDarwin  [BIOGRAPHY]
============================================================

--- TOP 100 UNIGRAMS ---

          ngram  count
1           one    103
2          much     82
3         years     73
4          time     70
5         could     65
..          ...    ...
480        mere      5
481  appearance      5
482   mentioned      5
483   examining      5
484    humboldt      5

[484 rows x 2 columns]

--- TOP 100 BIGRAMS ---

                    ngram  count
1           voyage beagle     14
2               two years     10
3               good deal     10
4                 one day      9
5          origin species      9
..                    ...    ...
452  heterostyled flowers      2
453        power movement      2
454             work book      2
455          thirty years      2
456           line poetry      2

[456 rows x 2 columns]

--- TOP 100 TRIGRAMS ---

                        ngram  count
1          gave much pleasure      4
2      became well acquainted      3
3            tour north wales      3
4             geolog soc proc      3
5    variation animals plants      3
..                        ...    ...
416     valuable fruit father      1
417        fruit father trees      1
418          father trees hid      1
419       trees hid shrubbery      1
420         hid shrubbery ran      1

[420 rows x 2 columns]

============================================================
  TheWonderfulWizardOfOz  [FANTASY]
============================================================

--- TOP 100 UNIGRAMS ---

         ngram  count
1         said    332
2    scarecrow    225
3           oz    164
4        great    142
5          tin    140
..         ...    ...
468    sitting      8
469      fruit      8
470     wanted      8
471     unless      8
472       bade      8

[472 rows x 2 columns]

--- TOP 100 BIGRAMS ---

              ngram  count
1      wicked witch     60
2      emerald city     57
3    said scarecrow     39
4       little girl     32
5    winged monkeys     30
..              ...    ...
382         oz made      3
383    wizard would      3
384   promised give      3
385   come tomorrow      3
386  scarecrow must      3

[386 rows x 2 columns]

--- TOP 100 TRIGRAMS ---

                           ngram  count
1              road yellow brick     12
2                get back kansas     11
3               send back kansas      9
4              wicked witch east      8
5         soldier green whiskers      8
..                           ...    ...
353  classed historical children      1
354  historical children library      1
355        children library time      1
356            library time come      1
357             time come series      1

[357 rows x 2 columns]

============================================================
  AliceInWonderland  [FANTASY]
============================================================

--- TOP 100 UNIGRAMS ---

       ngram  count
1       said    462
2     little    129
3        one    104
4       know     87
5       like     85
..       ...    ...
478     nine      5
479      kid      5
480  dropped      5
481    usual      5
482  morning      5

[482 rows x 2 columns]

--- TOP 100 BIGRAMS ---

                    ngram  count
1             mock turtle     57
2              march hare     31
3            white rabbit     22
4             said hatter     22
5               said mock     20
..                    ...    ...
387              end tail      2
388              let hear      2
389          hurry change      2
390  subject conversation      2
391          went eagerly      2

[391 rows x 2 columns]

--- TOP 100 TRIGRAMS ---

                  ngram  count
1      said mock turtle     20
2       said march hare     10
3     poor little thing      6
4     little golden key      5
5      white kid gloves      5
..                  ...    ...
348    brave think home      1
349  anything even fell      1
350       even fell top      1
351      fell top house      1
352    top house likely      1

[352 rows x 2 columns]

============================================================
  ThroughTheLookingGlass  [FANTASY]
============================================================

--- TOP 100 UNIGRAMS ---

            ngram  count
1            said    473
2           queen    189
3             one    155
4            know    126
5            like    124
..            ...    ...
470  triumphantly      6
471       gravely      6
472      consider      6
473          pair      6
474     provoking      6

[474 rows x 2 columns]

--- TOP 100 BIGRAMS ---

             ngram  count
1    humpty dumpty     56
2      white queen     35
3       queen said     29
4    looking glass     23
5      knight said     15
..             ...    ...
359      talk said      2
360   quite seemed      2
361   voice almost      2
362      goes long      2
363     air seemed      2

[363 rows x 2 columns]

--- TOP 100 TRIGRAMS ---

                        ngram  count
1          said humpty dumpty     14
2                 one one one      8
3         looking glass house      7
4          humpty dumpty said      7
5                    oh oh oh      5
..                        ...    ...
308      bale pleasance fairy      1
309      pleasance fairy tale      1
310       fairy tale contents      1
311     tale contents chapter      1
312  contents chapter looking      1

[312 rows x 2 columns]

============================================================
  GrimmsFairyTales  [FANTASY]
============================================================

--- TOP 100 UNIGRAMS ---

       ngram  count
1       said   1162
2       came    461
3       went    445
4        one    409
5     little    401
..       ...    ...
453  laughed     19
454     vain     19
455     cock     19
456    broke     19
457  grieved     19

[457 rows x 2 columns]

--- TOP 100 BIGRAMS ---

            ngram  count
1       old woman     56
2         one day     38
3    next morning     28
4      little man     28
5       long time     27
..            ...    ...
401    still said      5
402    came great      5
403    golden cup      5
404      man went      5
405    would said      5

[405 rows x 2 columns]

--- TOP 100 TRIGRAMS ---

                    ngram  count
1          said old woman      8
2    mother killed little      8
3     father grieved gone      8
4       sister loved best      8
5      laid kerchief took      8
..                    ...    ...
358        thee want said      2
359         lord sun moon      2
360   four footed animals      2
361         frog put head      2
362      plate sleep upon      2

[362 rows x 2 columns]

============================================================
  GulliversTravels  [FANTASY]
============================================================

--- TOP 100 UNIGRAMS ---

        ngram  count
1       could    394
2        upon    391
3       would    370
4       great    297
5         one    282
..        ...    ...
479      look     19
480     voice     19
481   numbers     19
482  thoughts     19
483     durst     19

[483 rows x 2 columns]

--- TOP 100 BIGRAMS ---

                ngram  count
1            among us     29
2       several times     27
3           two three     22
4    imperial majesty     22
5           feet high     22
..                ...    ...
469     great council      3
470       whole board      3
471       except upon      3
472  could comprehend      3
473        knew could      3

[473 rows x 2 columns]

--- TOP 100 TRIGRAMS ---

                    ngram  count
1    shall trouble reader      8
2       two hundred yards      7
3      man mountain shall      6
4        three four times      6
5      desired would give      5
..                    ...    ...
446    party volume would      1
447    volume would least      1
448     would least twice      1
449     least twice large      1
450      twice large made      1

[450 rows x 2 columns]

============================================================
  Frankenstein  [HORROR]
============================================================

--- TOP 100 UNIGRAMS ---

         ngram  count
1          one    206
2        could    197
3        would    184
4          yet    152
5          man    137
..         ...    ...
473   strength     15
474      close     15
475  reflected     15
476      cried     15
477    remorse     15

[477 rows x 2 columns]

--- TOP 100 BIGRAMS ---

                   ngram  count
1                old man     34
2        chapter chapter     23
3         native country     15
4     natural philosophy     14
5            taken place     13
..                   ...    ...
446              said ah      2
447       former studies      2
448           first care      2
449  modern philosophers      2
450           like child      2

[450 rows x 2 columns]

--- TOP 100 TRIGRAMS ---

                         ngram  count
1      chapter chapter chapter     22
2           letter mrs saville      4
3          mrs saville england      4
4    branch natural philosophy      3
5        return native country      3
..                         ...    ...
436       admiration must felt      1
437           must felt little      1
438          felt little proud      1
439       little proud captain      1
440      proud captain offered      1

[440 rows x 2 columns]

============================================================
  CallOfCthulu  [HORROR]
============================================================

--- TOP 100 UNIGRAMS ---

         ngram  count
1        could     37
2          one     36
3         cult     36
4    professor     32
5          men     32
..         ...    ...
475       life      3
476    eskimos      3
477     phrase      3
478     common      3
479    priests      3

[479 rows x 2 columns]

--- TOP 100 BIGRAMS ---

                   ngram  count
1       professor angell     14
2             bas relief     11
3               old ones     11
4           young wilcox      8
5     inspector legrasse      6
..                   ...    ...
453        barrier could      1
454        could meaning      1
455        meaning queer      1
456    relief disjointed      1
457  disjointed jottings      1

[457 rows x 2 columns]

--- TOP 100 TRIGRAMS ---

                                ngram  count
1                      great old ones      5
2             endless bacchanale ring      2
3              bacchanale ring bodies      2
4                    ring bodies ring      2
5                    bodies ring fire      2
..                                ...    ...
447         representing monster form      1
448             monster form diseased      1
449  somewhat extravagant imagination      1
450   extravagant imagination yielded      1
451  imagination yielded simultaneous      1

[451 rows x 2 columns]

============================================================
  Dracula  [HORROR]
============================================================

--- TOP 100 UNIGRAMS ---

         ngram  count
1         said    570
2          one    506
3        could    492
4           us    464
5         must    440
..         ...    ...
466  yesterday     28
467      laugh     28
468     horror     28
469    anxious     28
470     pretty     27

[470 rows x 2 columns]

--- TOP 100 BIGRAMS ---

              ngram  count
1         dr seward    117
2        mrs harker     69
3    lord godalming     67
4      seward diary     49
5        last night     47
..              ...    ...
404        days ago      5
405       pass away      5
406         two men      5
407     empty house      5
408      shall much      5

[408 rows x 2 columns]

--- TOP 100 TRIGRAMS ---

                           ngram  count
1                dr seward diary     49
2         seward diary september     14
3         harker journal october     14
4           seward diary october     11
5           seward diary chapter     10
..                           ...    ...
289              gums drawn back      2
290  westenra unopened september      2
291   unopened september dearest      2
292              child said come      2
293             took hand raised      2

[293 rows x 2 columns]

============================================================
  TalesOfPoe  [HORROR]
============================================================

--- TOP 100 UNIGRAMS ---

          ngram  count
1          upon    513
2           one    293
3         could    221
4         would    184
5          said    181
..          ...    ...
474        mean     16
475        lamp     16
476  occasioned     16
477     evident     16
478        wish     16

[478 rows x 2 columns]

--- TOP 100 BIGRAMS ---

                 ngram  count
1              old man     20
2               let us     17
3           said dupin     15
4                ha ha     14
5              ugh ugh     14
..                 ...    ...
456       seen several      2
457       deal trouble      2
458         thus lived      2
459  sufficiently well      2
460        dupin would      2

[460 rows x 2 columns]

--- TOP 100 TRIGRAMS ---

                        ngram  count
1                 ugh ugh ugh     13
2                    ha ha ha      9
3         valley many colored      7
4          many colored grass      7
5             actions man man      5
..                        ...    ...
411           would like hear      1
412         like hear details      1
413  hear details excessively      1
414   details excessively odd      1
415    excessively odd simple      1

[415 rows x 2 columns]

============================================================
  DrJekyllAndMrHyde  [HORROR]
============================================================

--- TOP 100 UNIGRAMS ---

             ngram  count
1         utterson    131
2             said    130
3               mr    124
4           jekyll    102
5             hyde    101
..             ...    ...
478  consciousness      5
479             th      5
480        tempted      5
481        unhappy      5
482         smiled      5

[482 rows x 2 columns]

--- TOP 100 BIGRAMS ---

                    ngram  count
1             mr utterson     74
2                 mr hyde     34
3               dr jekyll     29
4             said lawyer     20
5                 said mr     19
..                    ...    ...
429          quaintly let      1
430           let brother      1
431            brother go      1
432              go devil      1
433  character frequently      1

[433 rows x 2 columns]

--- TOP 100 TRIGRAMS ---

                         ngram  count
1             said mr utterson     16
2              mr utterson sir      4
3           mr utterson lawyer      3
4               dr jekyll home      3
5                 dr jekyll mr      2
..                         ...    ...
408       asleep street street      1
409      street street lighted      1
410  street lighted procession      1
411   lighted procession empty      1
412    procession empty church      1

[412 rows x 2 columns]

============================================================
  PrideAndPrejudice  [ROMANCE]
============================================================

--- TOP 100 UNIGRAMS ---

         ngram  count
1           mr    808
2        could    531
3        would    485
4         said    406
5          mrs    354
..         ...    ...
463        got     25
464  relations     25
465  persuaded     25
466      large     24
467      small     24

[467 rows x 2 columns]

--- TOP 100 BIGRAMS ---

              ngram  count
1        mr bingley    116
2      miss bingley     87
3        mr wickham     68
4         de bourgh     41
5         young man     38
..              ...    ...
350   younger girls      4
351    aunt philips      4
352    away without      4
353  turned towards      4
354     made slight      4

[354 rows x 2 columns]

--- TOP 100 TRIGRAMS ---

                     ngram  count
1           miss de bourgh     21
2        said miss bingley     10
3           mrs hurst miss      9
4       hurst miss bingley      9
5      ten thousand pounds      6
..                     ...    ...
219        mr wickham last      2
220  thousand pounds would      2
221  three thousand pounds      2
222       sister ten years      2
223    course mention name      2

[223 rows x 2 columns]

============================================================
  RomeoAndJuliet  [ROMANCE]
============================================================

--- TOP 100 UNIGRAMS ---

       ngram  count
1       thou    278
2        thy    170
3    capulet    163
4      nurse    149
5       thee    138
..       ...    ...
452      far      5
453   shrift      5
454     nine      5
455      sad      5
456    rough      5

[456 rows x 2 columns]

--- TOP 100 BIGRAMS ---

              ngram  count
1      lady capulet     60
2         thou hast     21
3      exeunt scene     16
4        good night     15
5     capulet house     13
..              ...    ...
303    tender thing      2
304   benvolio come      2
305       word thou      2
306   well mercutio      2
307  untimely death      2

[307 rows x 2 columns]

--- TOP 100 TRIGRAMS ---

                    ngram  count
1    capulet lady capulet      8
2      room capulet house      6
3      lady capulet nurse      6
4     capulet house scene      5
5         exeunt scene ii      5
..                    ...    ...
286          runn st away      1
287       dog house shall      1
288      house shall move      1
289      shall move stand      1
290       move stand take      1

[290 rows x 2 columns]

============================================================
  JaneEyre  [ROMANCE]
============================================================

--- TOP 100 UNIGRAMS ---

       ngram  count
1      would    665
2        one    595
3       said    584
4         mr    544
5      could    505
..       ...    ...
458    poole     32
459   narrow     31
460  curtain     31
461    money     31
462      try     31

[462 rows x 2 columns]

--- TOP 100 BIGRAMS ---

               ngram  count
1              ad le    135
2          miss eyre     45
3    mr brocklehurst     45
4            yes sir     35
5          mr rivers     33
..               ...    ...
381        good fire      4
382          one two      4
383      shook hands      4
384      said better      4
385     could endure      4

[385 rows x 2 columns]

--- TOP 100 TRIGRAMS ---

                      ngram  count
1              little ad le      9
2    twenty thousand pounds      6
3           right hand left      5
4         poor orphan child      5
5           three weeks ago      4
..                      ...    ...
246    five thousand pounds      2
247   thousand pounds would      2
248           sister let us      2
249         let us continue      2
250           sees man sees      2

[250 rows x 2 columns]

============================================================
  WutheringHeights  [ROMANCE]
============================================================

--- TOP 100 UNIGRAMS ---

         ngram  count
1        would    443
2       linton    406
3         said    375
4           mr    312
5          one    291
..         ...    ...
467      sweet     21
468    country     20
469     fellow     20
470  yesterday     20
471        six     20

[471 rows x 2 columns]

--- TOP 100 BIGRAMS ---

                 ngram  count
1           mrs linton     62
2    wuthering heights     61
3            mr linton     60
4           young lady     45
5          mr earnshaw     38
..                 ...    ...
394         going tell      3
395         till heard      3
396        linton face      3
397           hid face      3
398             fro th      3

[398 rows x 2 columns]

--- TOP 100 TRIGRAMS ---

                             ngram  count
1              seventy times seven      6
2              first seventy first      4
3                      let us hear      4
4                  mrs linton said      4
5             exclaimed mrs linton      4
..                             ...    ...
400     altogether another quarter      1
401          another quarter least      1
402    quarter least distinguished      1
403    least distinguished chatter      1
404  distinguished chatter tongues      1

[404 rows x 2 columns]

============================================================
  SenseAndSensibility  [ROMANCE]
============================================================

--- TOP 100 UNIGRAMS ---

        ngram  count
1       could    578
2         mrs    530
3       would    515
4        said    397
5       every    376
..        ...    ...
462  constant     22
463    merely     22
464      read     22
465    danger     22
466      easy     22

[466 rows x 2 columns]

--- TOP 100 BIGRAMS ---

              ngram  count
1      mrs dashwood    121
2    lady middleton     95
3       every thing     80
4       mrs ferrars     75
5     miss dashwood     70
..              ...    ...
356     said little      4
357   short silence      4
358        oh cried      4
359  something like      4
360      could well      4

[360 rows x 2 columns]

--- TOP 100 TRIGRAMS ---

                    ngram  count
1       said mrs dashwood     10
2       two thousand year      8
3      mrs dashwood could      7
4      miss dashwood said      7
5     two thousand pounds      7
..                    ...    ...
262   chapter vii chapter      1
263      vii chapter viii      1
264  chapter viii chapter      1
265       viii chapter ix      1
266    chapter ix chapter      1

[266 rows x 2 columns]

============================================================
  OnTheTrailOfTheSpacePirates  [SCI-FI]
============================================================

--- TOP 100 UNIGRAMS ---

         ngram  count
1       strong    506
2         said    301
3        astro    294
4       coxine    291
5         ship    248
..         ...    ...
470     either     11
471       many     11
472        ago     11
473  carefully     11
474  explained     11

[474 rows x 2 columns]

--- TOP 100 BIGRAMS ---

               ngram  count
1        solar guard    132
2        said strong     72
3     captain strong     64
4           sir said     58
5       three cadets     57
..               ...    ...
392   intercom radar      3
393   bridge control      3
394  command captain      3
395        blast sir      3
396     well corbett      3

[396 rows x 2 columns]

--- TOP 100 TRIGRAMS ---

                     ngram  count
1      solar guard officer     15
2             yes sir said     15
3           scar faced man     12
4              aye aye sir     12
5      solar guard captain     12
..                     ...    ...
381  attention bull coxine      2
382       flipped key open      2
383  twenty million credit      2
384     million credit pay      2
385        credit pay roll      2

[385 rows x 2 columns]

============================================================
  PlagueShip  [SCI-FI]
============================================================

--- TOP 100 UNIGRAMS ---

       ngram  count
1        rip    241
2        one    219
3      would    202
4      could    200
5      queen    148
..       ...    ...
465   thrust     12
466    story     12
467     home     12
468  machine     12
469  counter     12

[469 rows x 2 columns]

--- TOP 100 BIGRAMS ---

               ngram  count
1       cargo master     55
2        solar queen     28
3    captain jellico     25
4       free traders     23
5           com tech     20
..               ...    ...
364      tight tunic      2
365       foot queen      2
366     captain ship      2
367      master want      2
368    eysie officer      2

[368 rows x 2 columns]

--- TOP 100 TRIGRAMS ---

                          ngram  count
1                rip shook head      5
2       cargo master apprentice      4
3            rycke cargo master      4
4              crew solar queen      4
5           free trading spacer      3
..                          ...    ...
381     planet appeared largely      1
382    appeared largely clothed      1
383  largely clothed shimmering      1
384  clothed shimmering flowing      1
385   shimmering flowing carpet      1

[385 rows x 2 columns]

============================================================
  TheWarOfTheWorlds  [SCI-FI]
============================================================

--- TOP 100 UNIGRAMS ---

        ngram  count
1         one    202
2        upon    172
3    martians    166
4        said    166
5      people    159
..        ...    ...
473     forth     12
474   gripped     12
475    bushes     12
476   western     12
477     heads     12

[477 rows x 2 columns]

--- TOP 100 BIGRAMS ---

                   ngram  count
1            black smoke     25
2              came upon     17
3               far away     17
4             along road     15
5       handling machine     15
..                   ...    ...
422  cylinder artificial      2
423         good heavens      2
424          said ogilvy      2
425              man men      2
426        still glowing      2

[426 rows x 2 columns]

--- TOP 100 TRIGRAMS ---

                       ngram  count
1          twenty four hours      5
2       went railway station      3
3         hundred yards away      3
4        heard clatter hoofs      3
5           went dining room      3
..                       ...    ...
415  planet green vegetation      1
416    green vegetation grey      1
417    vegetation grey water      1
418        grey water cloudy      1
419  water cloudy atmosphere      1

[419 rows x 2 columns]

============================================================
  TheTimeMachine  [SCI-FI]
============================================================

--- TOP 100 UNIGRAMS ---

         ngram  count
1         time    207
2          one    118
3       little    114
4         upon    113
5         came    107
..         ...    ...
474      vague      6
475  suggested      6
476      cried      6
477      trick      6
478      front      6

[478 rows x 2 columns]

--- TOP 100 BIGRAMS ---

                 ngram  count
1       time traveller     64
2         time machine     39
3          medical man     24
4        little people     16
5            said time     14
..                 ...    ...
455     back presently      2
456  rayless obscurity      2
457         light soon      2
458          even mind      2
459         open space      2

[459 rows x 2 columns]

--- TOP 100 TRIGRAMS ---

                             ngram  count
1              said time traveller     12
2                 said medical man     11
3           palace green porcelain     10
4                 cannot move time      4
5                eight hundred two      4
..                             ...    ...
448  dimensioned fixed unalterable      1
449        fixed unalterable thing      1
450   unalterable thing scientific      1
451        thing scientific people      1
452    scientific people proceeded      1

[452 rows x 2 columns]

============================================================
  TwentyThousandLeagues  [SCI-FI]
============================================================

--- TOP 100 UNIGRAMS ---

            ngram  count
1         captain    644
2        nautilus    525
3            nemo    388
4             one    370
5             sea    357
..            ...    ...
473         small     20
474        slight     20
475  considerable     20
476         cause     20
477     necessary     20

[477 rows x 2 columns]

--- TOP 100 BIGRAMS ---

                   ngram  count
1           captain nemo    387
2           said conseil     53
3           said captain     45
4                 let us     34
5               sir said     33
..                   ...    ...
439           us captain      4
440         nets brought      4
441  beautiful specimens      4
442           lying side      4
443       light nautilus      4

[443 rows x 2 columns]

--- TOP 100 TRIGRAMS ---

                      ngram  count
1         said captain nemo     25
2               next day th     14
3      replied captain nemo     13
4         captain nemo went      9
5          sir said captain      9
..                      ...    ...
395  captain nemo conducted      2
396     turned captain nemo      2
397       captain nemo hand      2
398      last words escaped      2
399      words escaped lips      2

[399 rows x 2 columns]

## Genre-Level N-Gram Aggregation
Pools n-gram counts across all books within each genre, then takes the top `TOP_N`
per genre. A word that appears consistently across multiple books in a genre ranks
higher than one that dominates a single book — giving a more representative vocabulary.

In [81]:
from collections import defaultdict

# Sum n-gram counts across all books within the same genre
genre_counts = defaultdict(lambda: {t: Counter() for t in ['unigrams', 'bigrams', 'trigrams']})

for book, data in results.items():
    genre = data['genre']
    for ngram_type in ['unigrams', 'bigrams', 'trigrams']:
        for ngram, count in data[ngram_type]:
            genre_counts[genre][ngram_type][ngram] += count

# Take top-TOP_N per genre per n-gram type
genre_top = {}
for genre in sorted(genre_counts):
    genre_top[genre] = {
        ngram_type: genre_counts[genre][ngram_type].most_common(TOP_N)
        for ngram_type in ['unigrams', 'bigrams', 'trigrams']
    }

print(f"Genre-level top-{TOP_N} n-grams computed:\n")
for genre in sorted(genre_top):
    u = len(genre_top[genre]['unigrams'])
    b = len(genre_top[genre]['bigrams'])
    t = len(genre_top[genre]['trigrams'])
    print(f"  {genre:12}: {u} unigrams, {b} bigrams, {t} trigrams")

total = sum(len(genre_top[g][t]) for g in genre_top for t in ['unigrams', 'bigrams', 'trigrams'])
print(f"\nTotal vocabulary candidates: {total} (before cross-genre deduplication)")

Genre-level top-100 n-grams computed:

  biography   : 100 unigrams, 100 bigrams, 100 trigrams
  fantasy     : 100 unigrams, 100 bigrams, 100 trigrams
  horror      : 100 unigrams, 100 bigrams, 100 trigrams
  romance     : 100 unigrams, 100 bigrams, 100 trigrams
  sci-fi      : 100 unigrams, 100 bigrams, 100 trigrams

Total vocabulary candidates: 1500 (before cross-genre deduplication)

## Top 10 Unigrams per Genre
Aggregated across all books in each genre — shows the most genre-representative words.

In [82]:
comparison = {
    genre: [ngram for ngram, _ in genre_top[genre]['unigrams'][:10]]
    for genre in sorted(genre_top)
}

comp_df = pd.DataFrame(comparison)
comp_df.index = [f"#{i+1}" for i in range(10)]
print("Top 10 unigrams per genre (aggregated across books, stop words removed):\n")
display(comp_df)

Top 10 unigrams per genre (aggregated across books, stop words removed):

    biography fantasy horror romance   sci-fi
#1        one    said    one   would      one
#2      great     one   said   could     said
#3     little   could  could      mr  captain
#4       time   would  would    said    could
#5      would  little   upon     one    would
#6         mr    came     us     mrs     time
#7       many    went   must    must      two
#8       made    upon    man    well       us
#9       much   great   time    much   strong
#10     could    time  shall    miss      man

## Export Genre N-Grams to CSV
One CSV per n-gram type, one row per genre-level top-`TOP_N` entry.

In [83]:
for ngram_type in ['unigrams', 'bigrams', 'trigrams']:
    rows = []
    for genre in sorted(genre_top):
        for rank, (ngram, count) in enumerate(genre_top[genre][ngram_type], start=1):
            rows.append({
                'genre': genre,
                'rank':  rank,
                'ngram': ngram,
                'count': count,
            })
    df = pd.DataFrame(rows)
    out_path = f"ngrams/top100_{ngram_type}.csv"
    df.to_csv(out_path, index=False)
    print(f"Saved: {out_path}")

Saved: ngrams/top100_unigrams.csv
Saved: ngrams/top100_bigrams.csv
Saved: ngrams/top100_trigrams.csv

## Export Vocabulary for Classifier
Saves `vocabulary.csv` — the union of genre-level top-`TOP_N` n-grams across all five genres,
de-duplicated. The classifier notebook uses this list to build its TF-IDF feature matrix.

In [84]:
# Union of genre-level top-100 n-grams across all genres
all_ngrams = set()
for data in genre_top.values():
    for word,   _ in data['unigrams']:  all_ngrams.add(word)
    for phrase, _ in data['bigrams']:   all_ngrams.add(phrase)
    for phrase, _ in data['trigrams']:  all_ngrams.add(phrase)

n_uni = len({w for data in genre_top.values() for w, _ in data['unigrams']})
n_bi  = len({p for data in genre_top.values() for p, _ in data['bigrams']})
n_tri = len({p for data in genre_top.values() for p, _ in data['trigrams']})

vocab_df = pd.DataFrame(sorted(all_ngrams), columns=['word'])
vocab_df.to_csv('FeatureTrainingData/vocabulary.csv', index=False)
print(f"Vocabulary size: {len(vocab_df)} entries  ({n_uni} unigrams + {n_bi} bigrams + {n_tri} trigrams)")
print(f"Saved to 'FeatureTrainingData/vocabulary.csv'")

Vocabulary size: 1109 entries  (214 unigrams + 399 bigrams + 496 trigrams)
Saved to 'FeatureTrainingData/vocabulary.csv'

## Build Feature Vector CSV
Applies TF-IDF (restricted to the vocabulary) to every labelled text partition
and saves the result as a ready-to-train feature matrix.

**Requires:** `TestingData/partitions.csv` from `Book partitioner.ipynb`

**Outputs:**
- `FeatureTrainingData/featurevector.csv` — one row per partition, columns for `partition_id`, `genre`, and one TF-IDF score per vocabulary entry (unigrams + bigrams + trigrams)
- `FeatureTrainingData/vectorizer.pkl` — fitted vectorizer for transforming new unseen text

In [85]:
from sklearn.feature_extraction.text import TfidfVectorizer
import joblib

# Load labelled partitions (produced by Book partitioner.ipynb)
partitions = pd.read_csv('TestingData/partitions.csv')

# Full vocabulary: unigrams + bigrams + trigrams in sorted order (same as vocabulary.csv)
vocab_list = sorted(all_ngrams)

# Fit TF-IDF restricted to the shared vocabulary.
# ngram_range=(1,3) enables phrase matching; stop_words removes stopwords before
# generating n-grams so phrases match the stopword-filtered extraction logic.
vectorizer = TfidfVectorizer(
    vocabulary    = vocab_list,
    ngram_range   = (1, 3),
    stop_words    = 'english',
    sublinear_tf  = True,
    strip_accents = 'unicode',
    analyzer      = 'word',
    token_pattern = r'[a-z]+',
    lowercase     = True,
)

X = vectorizer.fit_transform(partitions['text'])
feature_names = vectorizer.get_feature_names_out()

# Assemble: partition_id | genre | feature_1 | feature_2 | ...
feat_df = pd.DataFrame(X.toarray(), columns=feature_names)
feat_df.insert(0, 'genre',        partitions['genre'].values)
feat_df.insert(0, 'partition_id', partitions['partition_id'].values)

feat_df.to_csv('FeatureTrainingData/featurevector.csv', index=False)
joblib.dump(vectorizer, 'FeatureTrainingData/vectorizer.pkl')

print(f"Saved: FeatureTrainingData/featurevector.csv")
print(f"  {feat_df.shape[0]} partitions  ×  {len(feature_names)} features")
print(f"  ({n_uni} unigram + {n_bi} bigram + {n_tri} trigram features)")
print(f"Saved: FeatureTrainingData/vectorizer.pkl")
feat_df.iloc[:3, :8]   # preview first few columns

Saved: FeatureTrainingData/featurevector.csv
  5000 partitions  ×  1109 features
  (214 unigram + 399 bigram + 496 trigram features)
Saved: FeatureTrainingData/vectorizer.pkl

,partition_id,genre,accompanied princess,accompanied princess wales,across,actions man man,ad le,ad le came
0,AutobiographyOfBenjaminFranklin_partition_a,biography,0.0,0.0,0.0,0.0,0.0,0.0
1,AutobiographyOfBenjaminFranklin_partition_b,biography,0.0,0.0,0.0,0.0,0.0,0.0
2,AutobiographyOfBenjaminFranklin_partition_c,biography,0.0,0.0,0.0,0.0,0.0,0.0